### ISSUE TITLE
visible  Discovery indexes for LDAP groups

### ISSUE THREAD

**Issue by ILyaMotkov** [opensearch-project/security#1006]
LDAP groups, when users get to the discovery tab, see all index pattern, which field binding must be set to that only the right given indexes are displayed?

my role.yaml
```
back:
  reserved: false
  cluster_permissions:
    - 'cluster_composite_ops'
  index_permissions:
    - index_patterns:
        - '.kibana-6'
        - '.kibana_*'
        - '.kibana'
      allowed_actions:
        - 'read'
```

and roles_mapping.yml
```
kibana_user:
  reserved: false
  backend_roles:
    - "kibanauser"
    - "back"
  description: "Maps kibanauser to kibana_user"
```
