### ISSUE TITLE
Parameters substitution in index_patterns

### ISSUE THREAD

**Issue by thethir13en** [opensearch-project/security#1106]
Hello!
I'm using proxy for authentication, in my environment. Opendistro_security gets attributes from proxy headers looks like 'X-Attr-*'. One of this headers contains kubernetes namespaces list, separated by comma, for example 'X-Attr-NS: default, ns1, ns2'. 

Can I substitute this attribute as a part of regular expression in index_patterns within role?
E.g.:
```
user_role:
      cluster_permissions:
        - "cluster_monitor"
        - "cluster_composite_ops"
      index_permissions:
        - index_patterns:
          - "${attr.proxy.ns}-*"
          allowed_actions:
          - "unlimited"
```

Expecting behavior same as regex ```(default|ns1|ns)-*```.
