### ISSUE TITLE
[BUG] Kibana USER gets authenticated as Kibana SERVER (even if user credentials are WRONG!)

### ISSUE THREAD

**Issue by GuiTeK** [opensearch-project/security#1279]
**Describe the bug**

Link to original post on the forum: https://discuss.opendistrocommunity.dev/t/kibana-server-authentication-overrides-kibana-user-authentication/6207

What I want to have for authentication is the following:
* **Client certificate** authentication between ES cluster and Kibana SERVER
* **Internal user database** authentication between Kibana USER and ES cluster

Whatever username/password I input in Kibana (even completely random/wrong credentials), **it will log me in as the Kibana _SERVER_ user** (the certificate common name is shown as the logged in user name in the Kibana UI) instead of the user with the username/password I typed.

So basically **anyone can type any username/password and they get logged in Kibana as the Kibana _server_**… weird, and of course very **insecure** (there is basically **no username/password** as _any_ username/password combination works).

Here’s my `config.yml` for the Security Plugin:
```yaml
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    kibana:
      multitenancy_enabled: false
    http:
      anonymous_auth_enabled: false
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal
      clientcert_auth_domain:
        description: "Authenticate via SSL client certificates (for Kibana Server)"
        http_enabled: true
        transport_enabled: true
        order: 2
        http_authenticator:
          type: clientcert
          config:
            username_attribute: cn
          challenge: false
        authentication_backend:
          type: noop
```

And here’s my `kibana.yml`:
```yaml
server.name: test-logs-kibana
server.host: 0.0.0.0
server.port: 5601

elasticsearch.hosts:
  - https://es1.test-logs.example.com:9200

# Use client certificate authentication to authenticate to the ElasticSearch cluster
elasticsearch.ssl.alwaysPresentCertificate: true
elasticsearch.ssl.certificateAuthorities: ["/etc/kibana/certs/ca.cert.pem"]
elasticsearch.ssl.certificate: /etc/kibana/certs/kb1.cert.pem
elasticsearch.ssl.key: /etc/kibana/certs/kb1.key.pem

# Use SSL for serving Kibana to clients
server.ssl.enabled: true
server.ssl.certificateAuthorities: ["/etc/kibana/certs/ca.cert.pem"]
server.ssl.certificate: /etc/kibana/certs/front.cert.pem
server.ssl.key: /etc/kibana/certs/front.key.pem

opendistro_security.multitenancy.enabled: false
```

**To Reproduce**
1. Start a new ES cluster
2. Start a new Kibana server
3. Modify the `config.yml` as shown above on the ES cluster
4. Apply the changes with `securityadmin.sh`
5. Modify the `kibana.yml` as shown above on the Kibana server
6. Restart the Kibana server to apply the changes
7. In a browser, go to the login page of the Kibana
8. Enter a random username and a random password which don't exist
9. Click on the user badge in the top right corner and see that you're logged in as the Kibana _server_

**Expected behavior**
* The user should be logged in as themselves, not as the Kibana server
* Wrong credentials shouldn't work

**Plugins**
* Security Plugin

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04
 - Elasticsearch Version: 7.10.2
 - Open Distro Security Version: 1.13.1.0
 - ODFE package (dpkg -s): 1.13.2-1
 - Kibana package (dpkg -s): 1.13.2

**Additional context**
N/A
