### ISSUE TITLE
readall_and_monitor static role not working as described

### ISSUE THREAD

**Issue by mhowlesb** [opensearch-project/security#1288]
https://github.com/opensearch-project/security/blob/b3932abfd2faba409a52e5dd77d26689e6eb4255/src/main/resources/static_config/static_roles.yml#L143-L155

https://discuss.opendistrocommunity.dev/t/rolemapped-backend-role-doesnt-have-assigned-permissions/6262

The `readall_and_monitor` role, as described indicates that a user/backend role that has been mapped to the `readall_and_monitor` role should be able to read all data, and read/get all aliases (as the `cluster_composite_ops_ro` would indicate). However, the `cluster_composite_ops_ro` actiongroup is a cluster permission and the `indices:admin/aliases/get` permission needs to be under index permissions.

I recommend the following:

```
readall_and_monitor:
  reserved: true
  hidden: false
  static: true
  description: "Provide the minimum permissions to readall indices and monitor the cluster"
  cluster_permissions:
  - "cluster_monitor"
  - "cluster_composite_ops_ro"
  index_permissions:
  - index_patterns:
    - "*"
    allowed_actions:
    - "read"
    - "indices:admin/aliases/exists"
    - "indices:admin/aliases/get"
    - "indices_monitor"
```
