### ISSUE TITLE
[BUG]  Increasing read times with opensecurity under certain conditions

### ISSUE THREAD

**Issue by sezuan** [opensearch-project/security#1451]
**Describe the bug**

Under high read load and a the *existence* of an unused ldap configuration and client cert authentication the read request are getting increasingly slower. After removal of unused ldap configuration or setting the security cache ttl to 0  the requests are fast as expected.

**To Reproduce**

1. Use client cert authentication, the bug won't occur with basic auth.
2. Add an authz section with a ldap lookup. Add all cert users to skip_users.
3. Put read load and measure time.

I tested that on a 3 node cluster with about 200 million documents. 2000 concurrent connections, distributed across all three nodes. With pattern read - sleep 333ms - read - ....

4. The read duration will increase over time.

Here's a redacted example of my security config.
```
  dynamic:
    filtered_alias_mode: "warn"
    disable_rest_auth: false
    disable_intertransport_auth: false
    respect_request_indices_options: false
    license: null
    kibana:
      multitenancy_enabled: true
      server_username: "kibanaserver"
      index: ".kibana"
    http:
      anonymous_auth_enabled: true
      xff:
        enabled: true
        internalProxies: "<redacted:regex>"
        remoteIpHeader: "X-Forwarded-For"
    authc:
      clientcert_auth_domain:
        description: "Authenticate via SSL client certificates"
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: clientcert
          config:
            username_attribute: cn  #optional, if omitted DN becomes username
          challenge: false
        authentication_backend:
          type: "noop"
    authz:
      roles_from_myldap:
        http_enabled: true
        transport_enabled: false
        authorization_backend:
          type: "ldap"
          config:
            enable_ssl: true
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: true
            hosts:
            - "<redacted:ldap-server>"
            bind_dn: "<redacted:bind_dn>"
            password: "<redacted:password>"
            rolesearch: "(member={0})"
            userroleattribute: null
            userrolename: "disabled"
            rolename: "cn"
            resolve_nested_roles: true
            rolebase: "<redacted:rolebase>"
            usersearch: "(uid={0})"
            skip_users:
            - <redacted:various internal_users>
            - <redacted:*.domain which matches the client certs>
            - "opendistro_security_anonymous"
        description: "Migrated from v6"
    auth_failure_listeners: {}
    do_not_fail_on_forbidden: false
    multi_rolespan_enabled: false
    hosts_resolver_mode: "ip-only"
    transport_userrname_attribute: null
    do_not_fail_on_forbidden_empty: false
```

**Expected behavior**

The read duration should be more less constant. There should be no difference between client cert authentication and basic authenctication.

**Plugins**

opendistro_security 1.9.0.0

**Screenshots**

Here's a typical example. At the beginning it's fast, then the read time increases. After few minutes the authz part was removed and the cache flushed. After that, the read time is good.

![example1](https://user-images.githubusercontent.com/202755/134119810-9fe098f6-a747-460c-a6a9-cbdfa7d607dc.png)

There a two other ways to mitigate that:

Disable opendistro_security cache (`opendistro_security.cache.ttl_minutes: 0`)

![disable-cache](https://user-images.githubusercontent.com/202755/134120155-ff39b5ca-57ac-4aa1-a1a7-73129c86f43f.png)

Continiously flushing the cache:

![flushing-cache](https://user-images.githubusercontent.com/202755/134120240-62f728e1-92ac-458d-9d38-56baa4594098.png)

The flamegraph shows that getting data from the cache needs much more time when the issue occurs:

Without the authz/ldap section:
![fg1](https://user-images.githubusercontent.com/202755/134120488-69ed803e-5bb8-4451-9f6d-79c97b656484.png)

With auth/ldap section.
![fg2](https://user-images.githubusercontent.com/202755/134120492-dc62f748-0a89-4432-9df0-48f99364664f.png)

**Host/Environment (please complete the following information):**
 - OS: Debian / Buster
 - Elasticsearch 7.8.0
 - Opendistro seucrity 1.9.0.0

** Discussions on opendistrocomminity:

- https://discuss.opendistrocommunity.dev/t/performance-impact-using-client-certificate-authentication/6834
