### ISSUE TITLE
[BUG] Self signed admin certs not working proper

### ISSUE THREAD

**Issue by yacinelazaar** [opensearch-project/security#1506]
Im not quite sure about this one. I have self signed certs for nodes and admin and the opensearch cluster boots fine and show green status.
When i try to restore a snapshot using admin certs i get “Unauthorized”
![image](https://user-images.githubusercontent.com/1111396/143913101-4f64f4a3-dd7c-429d-8c85-a86997d1f223.png)

Yet when I run the security admin tool, the certs are accepted. how come?
![image](https://user-images.githubusercontent.com/1111396/143913344-dde6f153-c5d3-4c0c-8a8c-0efb862a6637.png)

Any help would be greatly appreciated.
Thanks.

**Comment by pawelw1** [comment]
@yacinelazaar  what user is defined in "plugins.security.authcz.admin_dn:" in opensearch.yml?

**Comment by yacinelazaar** [comment]
@pawelw1 
`authcz:
     admin_dn:
     - 'CN=admin-user,OU=Devops,O=Company,L=NJ,C=US'`

**Comment by pawelw1** [comment]
@yacinelazaar what is DN in your admin PEM?

**Comment by yacinelazaar** [comment]
Here is all the cert's details for whats worth
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            XXX
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = logging.svc.cluster.local
        Validity
            Not Before: Nov 30 10:45:42 2021 GMT
            Not After : Feb 28 10:45:42 2022 GMT
        Subject: C = US, L = NJ, O = Company, OU = Devops, CN = admin-user
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    XXXX
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Authority Key Identifier: 
                keyid:XXX

    Signature Algorithm: sha256WithRSAEncryption
         XXX
```

**Comment by dredwilliams** [comment]
@yacinelazaar - do you have certificate authentication enabled in your config.yml file?  It is off by default.

I also notice that your CN in the admin cert is 'admin-user' -- do you have an internal user defined for this username (or at least is 'admin-user' mapped to any roles)?  OpenSearch (by default, anyway) will use the CN as the username and try to resolve permissions that way -- if certificate authentication is enabled.

**Comment by dredwilliams** [comment]
Linking to the related thread in the discussion boards:

https://discuss.opendistrocommunity.dev/t/admin-certificates-not-working-properly/7770

**Comment by yacinelazaar** [comment]
@dredwilliams
I actually generated a new cert to map the CN to an existing admin user that can take snapshots. Restated the cluster with new admin_dn.
I believe cert auth is enabled. Here is my config.yml
```
_meta:
          type: "config"
          config_version: 2

        config:
          dynamic:
            kibana:
              multitenancy_enabled: true
              server_username: ${OSD_SERVER_USERNAME}
              index: '.kibana'
            do_not_fail_on_forbidden: false
            http:
              anonymous_auth_enabled: false
              xff:
                enabled: false
                #internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
                internalProxies: '.*' # trust all internal proxies, regex pattern
                remoteIpHeader:  'x-forwarded-for'
                ###### see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html for regex help
                ###### more information about XFF https://en.wikipedia.org/wiki/X-Forwarded-For
                ###### and here https://tools.ietf.org/html/rfc7239
                ###### and https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve
            authc:
              clientcert_auth_domain:
                description: "Authenticate via SSL client certificates"
                http_enabled: true
                transport_enabled: true
                order: 0
                http_authenticator:
                  type: clientcert
                  config:
                    username_attribute: cn #optional, if omitted DN becomes username
                  challenge: false
                authentication_backend:
                  type: noop
              basic_internal_auth_domain:
                description: "Authenticate via HTTP Basic against internal users database"
                http_enabled: true
                transport_enabled: true
                order: 1
                http_authenticator:
                  type: basic
                  challenge: true
                authentication_backend:
                  type: intern
```
I also have the setting `plugins.security.http.client`_mode set as OPTIONAL in opensearch.yml.
```
plugins:
      security:
        ssl:
          transport:
            pemcert_filepath: elk-transport-crt.pem
            pemkey_filepath: elk-transport-key.pem
            pemtrustedcas_filepath: ca.pem
            enforce_hostname_verification: false
          http:
            clientauth_mode: OPTIONAL
```
