### ISSUE TITLE
[BUG] Opensearch 1.2.3 JWT authentication won't work in the most basic setup

### ISSUE THREAD

**Issue by sandervandegeijn** [opensearch-project/security#1556]
**Describe the bug**
I'm trying to get openid working with AzureAD. This was a pain in the ass, couldn't get it to work (same error as the one below btw), so I switched to plain JWT's to try things out. I followed the instructions in the documentation to the letter as far as I know, also read the SearchGuard documentation which doesn't deviate from the opensearch instructions.

Error:

![image](https://user-images.githubusercontent.com/2643715/148206346-dbcbecea-82ac-4699-837d-9fed3f3902d2.png)

The JWT is picked up correctly from the Authorization header (bearer).

The JWT (link):
https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwicm9sZXMiOiJhZG1pbiIsImlhdCI6MTUxNjIzOTAyMn0.kqZmTrqKEOJkZq7e4oSUX0O9DC2wEi75jubvUfbT2J6aLtmyCu8By2yL_m8DfwQVNDVCQbD3VAlMi82voG6-1x6ndTR_FHYUP6dFg0n5CkS0nJS_txj4a62AJivmlcR99CMQaAPBU-y25D4-lWNlXWRwCQ92lWAx1-UZtEX4bJ7oq3tptMg0QD0nFTLx9cOFidvgMxtzMD02GQO47XJ7iMGDxExk3bxzUp1mL0l2sE0ctfPvooaXOz06Fd7fA4-F6K1P7AdC1kKts7j5KjJnSNy3FhfcYdNKN2L8nOOaMXv08c6UnpLTQ5Q_1yi727NxSAik9gTaxO22tEgIdTtWqw&publicKey=-----BEGIN%20PUBLIC%20KEY-----%0AMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu1SU1LfVLPHCozMxH2Mo%0A4lgOEePzNm0tRgeLezV6ffAt0gunVTLw7onLRnrq0%2FIzW7yWR7QkrmBL7jTKEn5u%0A%2BqKhbwKfBstIs%2BbMY2Zkp18gnTxKLxoS2tFczGkPLPgizskuemMghRniWaoLcyeh%0Akd3qqGElvW%2FVDL5AaWTg0nLVkjRo9z%2B40RQzuVaE8AkAFmxZzow3x%2BVJYKdjykkJ%0A0iT9wCS0DRTXu269V264Vf%2F3jvredZiKRkgwlL9xNAwxXFg0x%2FXFw005UWVRIkdg%0AcKWTjpBP2dPwVZ4WWC%2B9aGVd%2BGyn1o0CLelf4rEjGoXbAAEgAqeGUxrcIlbjXfbc%0AmwIDAQAB%0A-----END%20PUBLIC%20KEY-----

config.yml (loaded with security-tool):
```
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      saml_auth:
        order: 1
        description: "SAML provider"
        http_enabled: true
        transport_enabled: false
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: https://yadda/federationmetadata/2007-06/federationmetadata.xml
              entity_id: http://yadda/adfs/services/trust
            sp:
              entity_id: https://${url-dashboards}/
              #forceAuthn: true
            kibana_url: https://${url-dashboards}/
            subject_key: NameID
            roles_key: CustomRole
            exchange_key: yadda
        authentication_backend:
          type: noop
      jwt_auth_domain:
        description: "Authenticate via Json Web Token"
        http_enabled: true
        transport_enabled: true
        order: 2
        http_authenticator:
          type: jwt
          challenge: false
          config:
            signing_key: |-
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu1SU1LfVLPHCozMxH2Mo4lgOEePzNm0tRgeLezV6ffAt0gunVTLw7onLRnrq0/IzW7yWR7QkrmBL7jTKEn5u+qKhbwKfBstIs+bMY2Zkp18gnTxKLxoS2tFczGkPLPgizskuemMghRniWaoLcyehkd3qqGElvW/VDL5AaWTg0nLVkjRo9z+40RQzuVaE8AkAFmxZzow3x+VJYKdjykkJ0iT9wCS0DRTXu269V264Vf/3jvredZiKRkgwlL9xNAwxXFg0x/XFw005UWVRIkdgcKWTjpBP2dPwVZ4WWC+9aGVd+Gyn1o0CLelf4rEjGoXbAAEgAqeGUxrcIlbjXfbcmwIDAQAB
              -----END PUBLIC KEY-----
            jwt_header: "Authorization"
            jwt_url_parameter: jwt
            roles_key: roles
            subject_key: app_displayname
        authentication_backend:
          type: noop
      clientcert_auth_domain:
        description: "Authenticate via SSL client certificates"
        http_enabled: false
        transport_enabled: false
        order: 3
        http_authenticator:
          type: clientcert
          config:
            username_attribute: cn #optional, if omitted DN becomes username
          challenge: false
        authentication_backend:
          type: noop
    authz:
```

**Expected behavior**
JWT is accepted and used for authentication

**Plugins**
Default docker image plus s3 repository plugin

**Host/Environment (please complete the following information):**
Default docker image in k8s
