### ISSUE TITLE
Proxy auth does not work

### ISSUE THREAD

**Issue by dmnfortytwo** [opensearch-project/security#165]
Hi all!

elasticsearch-oss 7.2.1
opendistro-alerting 1.2.1.0-1
opendistro-job-scheduler 1.2.1.0-1
opendistro-performance-analyzer 1.2.1.0-1
opendistro-security 1.2.1.0-0
opendistro-sql 1.2.1.0-1
opendistroforelasticsearch 1.2.1-1
opendistroforelasticsearch-kibana 1.2.1

/etc/kibana/kibana.yml:
```
elasticsearch.hosts: https://localhost:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization", "x-proxy-user", "x-proxy-roles", "x-forwarded-for"]

logging.dest: "/var/log/kibana/kibana.log"
logging.quiet: false
logging.silent: false
logging.verbose: true

opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]
opendistro_security.auth.type: 'proxy'
```

securityconfig/config.yml:
```
config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: true
        internalProxies: '.*' # regex pattern
        remoteIpHeader:  'x-forwarded-for'
        proxiesHeader:   'x-forwarded-by'
        trustedProxies: '.*'
    authc:
      proxy_auth_domain:
        description: "Authenticate via proxy"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "x-proxy-user"
            roles_header: "x-proxy-roles"
        authentication_backend:
          type: noop
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 4
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
```
sample entry from kibana log:
```
{
  "type": "response",
  "@timestamp": "2019-11-15T18:13:45Z",
  "tags": [],
  "pid": 21010,
  "method": "get",
  "statusCode": 401,
  "req": {
    "url": "/app/kibana",
    "method": "get",
    "headers": {
      "x-proxy-user": "myusername",
      "x-proxy-roles": "admin",
      "host": "kibana-gce-be-4.project.domain.net",
      "x-real-ip": "46.188.xx.xx",
      "x-forwarded-for": "46.188.xx.xx",
      "x-forwarded-proto": "https",
      "connection": "close",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0",
      "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "accept-language": "en-GB,en;q=0.5",
      "accept-encoding": "gzip, deflate, br",
      "upgrade-insecure-requests": "1",
      "cache-control": "max-age=0"
    },
    "remoteAddress": "127.0.0.1",
    "userAgent": "127.0.0.1"
  },
  "res": {
    "statusCode": 401,
    "responseTime": 50,
    "contentLength": 9
  },
  "message": "GET /app/kibana 401 50ms - 9.0B"
}
```
What I expect to get when I open new browser window pointing to kibana installation?
I see kibana and I am logged in as myself without entering any credentials (as I am already logged in at my reverse proxy sso point)
What actually happens?
I see a basic auth popup asking for l/p (note status code from sample log message).

Please help, I believe there is some small thing I am missing that prevents opendistro from working as I expect.

Thank you.
