### ISSUE TITLE
[BUG] Security plugin affects deprecation feature

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/security#1731]
**Describe the bug**
The OpenSearch server has a nice feature to warn user if used functions will be deprecated in future versions. Unfortunately, security plugin affects this feature.
Detected when running [OpenSearch .Net client](https://github.com/opensearch-project/opensearch-net) integration tests.

**To Reproduce**
1. Run integration test with security:
```
./build.sh integrate 1.3.0 readonly random:test_only_one deprecationlogging --report
```
There is **1 deprecation**:
```
Warning: 299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "Deprecated aggregation order key [_term] used, replaced by [_key]"
```
2. Run integration test without security - you will receive **3 deprecations**:
```
Warning: 299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "Deprecated aggregation order key [_term] used, replaced by [_key]" 
Warning: 299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "OpenSearch requires that a [field] parameter is provided when a [seed] is set" 
Warning: 299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "Loading the fielddata on the _id field is deprecated and will be removed in future versions. If you require sorting or aggregating on this field you should also include the id in the body of your documents, and map this field as a keyword field that has [doc_values] enabled" 
```
3. Compare results

The [test](https://github.com/opensearch-project/opensearch-net/blob/main/tests/Tests/ClientConcepts/Troubleshooting/DeprecationLogging.doc.cs) runs the following request:
```
{
  "aggs": {
    "states": {
      "terms": {
        "field": "state.keyword",
        "order": [
          {
            "_term": "asc"
          }
        ]
      }
    }
  },
  "query": {
    "function_score": {
      "functions": [
        {
          "random_score": {
            "seed": 1337
          }
        }
      ],
      "query": {
        "match_all": {}
      }
    }
  },
  "size": 0
}
```
on index `project`:
```
/project/_search?pretty=true&error_trace=true&typed_keys=true&routing=ignoredefaultcompletedhandler
```

**Notes**
1. Tests don't support security configuration, it is hardcoded. See [PR #19](https://github.com/Bit-Quill/opensearch-net/pull/19
) how to modify the behavior locally.
2. Tests support released versions of OpenSearch only. Unfortunately, it is impossible to run test on dev builds.

**Expected behavior**
Security plugin should not affect deprecations.

**Plugins**
mapper-murmur3

**Attachments**
1. Server logs with security: [deprecationlogging-sec.zip](https://github.com/opensearch-project/security/files/8391782/deprecationlogging-sec.zip)
2. `tcpdump` (`wireshark` compatible) network traffic dump on test with security (see packets 236 and 238): [tcpdump.zip](https://github.com/opensearch-project/security/files/8391789/tcpdump.zip)
3. Server log without security: [deprecationlogging-nosec.zip](https://github.com/opensearch-project/security/files/8391808/deprecationlogging-nosec.zip)
5. `tcpdump` dump on test without security (packets 231 and 233): [tcpdump.zip](https://github.com/opensearch-project/security/files/8391812/tcpdump.zip)

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 20.04 on WSL 2
 - Version: 1.3.0
- `config/opensearch.yml`:
```yaml
plugins.security.ssl.transport.pemcert_filepath: esnode.pem
plugins.security.ssl.transport.pemkey_filepath: esnode-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.http.enabled: false
plugins.security.ssl.http.pemcert_filepath: esnode.pem
plugins.security.ssl.http.pemkey_filepath: esnode-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
plugins.security.allow_unsafe_democertificates: true
plugins.security.allow_default_init_securityindex: true
plugins.security.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test, C=de

plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opensearch-notifications-*", ".opensearch-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]

plugins.security.disabled: false
```
