### ISSUE TITLE
[BUG] Getting `security_exception` with empty list of missing permissions

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/security#1732]
Detected when running [OpenSearch .Net client](https://github.com/opensearch-project/opensearch-net) integration tests.

**To Reproduce**
1. Run integration test with security (see [PR #19](https://github.com/Bit-Quill/opensearch-net/pull/19):
```
./build.sh integrate 1.3.0 writable random:test_only_one deletealias --report
```
[The test](https://github.com/opensearch-project/opensearch-net/blob/main/tests/Tests/Indices/AliasManagement/DeleteAlias/AliasDeleteApiTests.cs) goes to delete alias by making `DELETE` request to
```
/_all/_alias/osc-initializerasync-45a48687-alias?pretty=true&error_trace=true
```
and gets
```
"type" : "security_exception",
"reason" : "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
```
Pay attention that permissions list is empty. `stack_trace` is omitted here.

**Expected behavior**
A clear and concise description of which permissions are missing should be sent.

**Plugins**
- analysis-icu
- analysis-kuromoji
- analysis-nori
- analysis-phonetic
- ingest-attachment
- mapper-murmur3

**Attachments**
1. Server logs (with security): [deletealias-sec.zip](https://github.com/opensearch-project/security/files/8392195/deletealias-sec.zip)
2. `tcpdump` (`wireshark` compatible) network traffic dump on test with security (see packets 232 and 234): [tcpdump.zip](https://github.com/opensearch-project/security/files/8392201/tcpdump.zip)
3. Test report with security: [junit-Tests-NETCoreApp50-test-results.txt](https://github.com/opensearch-project/security/files/8392247/junit-Tests-NETCoreApp50-test-results.txt)
4. Server logs (without security): [deletealias-nosec.zip](https://github.com/opensearch-project/security/files/8392232/deletealias-nosec.zip)
5. `tcpdump` dump without security: [tcpdump.zip](https://github.com/opensearch-project/security/files/8392236/tcpdump.zip)

**Host/Environment (please complete the following information):**
- OS: Ubuntu 20.04 on WSL 2
- Version: 1.3.0
- `config/opensearch.yml`:
```yaml
plugins.security.ssl.transport.pemcert_filepath: esnode.pem
plugins.security.ssl.transport.pemkey_filepath: esnode-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.http.enabled: false
plugins.security.ssl.http.pemcert_filepath: esnode.pem
plugins.security.ssl.http.pemkey_filepath: esnode-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
plugins.security.allow_unsafe_democertificates: true
plugins.security.allow_default_init_securityindex: true
plugins.security.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test, C=de

plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opensearch-notifications-*", ".opensearch-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]

plugins.security.disabled: false
```
