### ISSUE TITLE
Issue while setting up OpenID Connect with Google

### ISSUE THREAD

**Issue by mr-karan** [opensearch-project/security#176]
So, I'm trying to use Google OAuth2 as Open ID Connect Provider and facing some issues. Google has an Open ID Connect URL at `https://accounts.google.com/.well-known/openid-configuration` as mentioned in the docs [here](https://developers.google.com/identity/protocols/OpenIDConnect#discovery). It also has the field `jwks_uri` which points to `https://www.googleapis.com/oauth2/v3/certs`. However when I used the OpenID Connect config for security plugin, I am getting errors as:

```
odfe-node1    | [2019-12-06T13:01:52,454][WARN ][o.a.c.r.s.j.j.JwsCompactConsumer] [odfe-node1] Compact JWS does not have 3 parts
```

Open ID Connect Config:

```
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: https://accounts.google.com/.well-known/openid-configuration
        authentication_backend:
          type: noop
```

I don't seem to figure out what's going wrong here, can anyone help with pointers?
