### ISSUE TITLE
[BUG] ldap config setting `custom_attr_allowlist` does not do anything.

### ISSUE THREAD

**Issue by Martin-Kemp** [opensearch-project/security#2032]
**What is the bug?**
Ldap config setting `custom_attr_allowlist` which is supposed to limit the attributes searched for does not appear to do anything.

**How can one reproduce the bug?**
1. Download the example docker-compose files here: https://opensearch.org/docs/2.2/security-plugin/configuration/ldap/
2. Add some custom attributes to the config.yml file.
3. `docker-compose up`
4. Run a query against the api. The example in the docs will do.
5. Check logs of the ldap container.
6. You'll notice the search does not limit the attributes:
```
62fcbc4b conn=1013 op=1 SRCH base="ou=People,dc=example,dc=org" scope=2 deref=3 filter="(cn=psantos)"
62fcbc4b conn=1013 op=1 SRCH attr=* +
```

**What is the expected behavior?**
Attributes listed in `custom_attr_allowlist` should be filtered out, this should be evident in the ldap logs. Expected output:
```
62fcbc4b conn=1013 op=1 SRCH base="ou=People,dc=example,dc=org" scope=2 deref=3 filter="(cn=psantos)"
62fcbc4b conn=1013 op=1 SRCH attr=attribute1
```

**What is your host/environment?**
 - OS: Ubuntu WSL2. Also tested on other distros

**Comment by peternied** [comment]
@Martin-Kemp Thanks for filing this issue

**Comment by Martin-Kemp** [comment]
@peternied no problem. Let me know if it's not clear enough or you can't reproduce it.

**Comment by Martin-Kemp** [comment]
It looks like the `custom_attr_allowlist` doesn't end up in the user object's attributes.

I ran the test `testCustomAttributes`:

```
settings = Settings.builder()
        .putList(ConfigConstants.LDAP_HOSTS, "127.0.0.1:4", "localhost:" + ldapPort)
        .put(ConfigConstants.LDAP_AUTHC_USERSEARCH, "(uid={0})")
        .putList(ConfigConstants.LDAP_CUSTOM_ATTR_WHITELIST, "*objectclass*","entryParentId")
        .build();

user = (LdapUser) new LDAPAuthenticationBackend(settings, null).authenticate(new AuthCredentials("jacksonm", "secret"
        .getBytes(StandardCharsets.UTF_8)));

Assert.assertEquals(user.getCustomAttributesMap().toString(), 2, user.getCustomAttributesMap().size());
```

Then forcing it to fail with:

```
Assert.assertEquals(user.getCustomAttributesMap().toString(), 1, user.getCustomAttributesMap().size());
```

We can then see the custom attributes `*objectclass*` and `entryParentId` don't appear in the users object's attributes:

```
java.lang.AssertionError: {ldap.original.username=jacksonm, ldap.dn=cn=Michael Jackson,ou=people,o=TEST} expected:<1> but was:<2>
```

**Comment by peternied** [comment]
@Martin-Kemp  I think I found the source of the issue while doing code inspection, the value is `custom_attr_whitelist` in the codebase- can you adjust the setting and see if this resolves your issue?

Assuming this lets you work around it, we need to update the key to the inclusive terminology `allowlist` and we need to fix the documentation until this variant is avaliable.

**Comment by Martin-Kemp** [comment]
@peternied Thanks for the suggestion, I have tried using `custom_attr_whitelist` too but still the same issue:

```
62ff304d conn=1003 op=1 SRCH base="ou=People,dc=example,dc=org" scope=2 deref=3 filter="(cn=psantos)"
62ff304d conn=1003 op=1 SRCH attr=* +
```

The problem is that `SRCH attr=* +` shows that we're still requesting all attributes from the ldap server.

Could you try to reproduce the issue on your side? It's quite quick to do with the zip file supplied in the documentation. Just add:

```
custom_attr_whitelist:
              - attribute1
```

to `config.dynamic.authz.ldap_roles.authorization_backend.config` in the `config.yml` file. Like this:

```
---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      internal_auth:
        order: 0
        description: "HTTP basic authentication using the internal user database"
        http_enabled: true
        transport_enabled: true
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      ldap_auth:
        order: 1
        description: "Authenticate using LDAP"
        http_enabled: true
        transport_enabled: true
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: ldap
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: true
            hosts:
            - openldap:389
            bind_dn: cn=readonly,dc=example,dc=org
            password: changethistoo
            userbase: ou=People,dc=example,dc=org
            usersearch: (cn={0})
            username_attribute: cn

    authz:
      ldap_roles:
        description: "Authorize using LDAP"
        http_enabled: true
        transport_enabled: true
        authorization_backend:
          type: ldap
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: true
            hosts:
            - openldap:389
            bind_dn: cn=readonly,dc=example,dc=org
            password: changethistoo
            userbase: ou=People,dc=example,dc=org
            usersearch: (cn={0})
            username_attribute: cn
            skip_users:
              - admin
              - kibanaserver
            rolebase: ou=Groups,dc=example,dc=org
            rolesearch: (uniqueMember={0})
            userroleattribute: null
            userrolename: disabled
            rolename: cn
            resolve_nested_roles: false
            custom_attr_whitelist:
              - attribute1
 ```

Also change the version of opensearch in the `docker-compose` file, it's outdated (I opened an issue about that too: https://github.com/opensearch-project/documentation-website/issues/905)

Then just check the logs of the ldap container when you run the query supplied in the documentation.
