### ISSUE TITLE
[BUG] OpenID Connect redirects to "/" even if server.basePath is set

### ISSUE THREAD

**Issue by cebor** [opensearch-project/security#2105]
**What is the bug?**
Since i upgraded from 1.3.0 to 2.3.0 Opensearch-Dashboards configured with OICD always redirects to "/" not to the value defined in `server.basePath`.

**What is the expected behavior?**
After a successful login it should redirect to the value defined in `server.basePath`

**What is your host/environment?**
 - OS: docker on ubuntu 22.04
 - Version 2.3.0
 - Plugins: security

**Do you have any screenshots?**
![Screenshot 2022-09-23 at 14 14 11](https://user-images.githubusercontent.com/1576120/191958184-de2aa44a-f446-4524-8c26-f066a6559dde.png)

Here in this screenshot you can see the redirect from oicd host back to the opensearch-dashboards auth works, but after that it redirects always to "/", expected value here should be "/dynrep"

**Do you have any additional context?**

opensearch-dashboards.yml
```yml
server.name: kibana
server.host: 0.0.0.0
server.basePath: /dynrep
opensearch.hosts: https://localhost:9200
opensearch.ssl.verificationMode: none
opensearch.username: kibanaserver
opensearch.password: kibanaserver
opensearch.requestHeadersWhitelist: ["Authorization", "securitytenant"]

opensearch_security.multitenancy.enabled: true
opensearch_security.multitenancy.tenants.preferred: ["Global", "Private"]
opensearch_security.readonly_mode.roles: ["kibana_read_only"]

opensearch_security.auth.type: "openid"
opensearch_security.openid.connect_url: "https://myoicdhost/.well-known/openid-configuration"
opensearch_security.openid.client_id: "foo"
opensearch_security.openid.client_secret: "bar"
opensearch_security.openid.logout_url: "https://myoicdhost/logout"
opensearch_security.openid.scope: "email"
opensearch_security.openid.base_redirect_url: "https://myhostname/dynrep"

# Use this setting if you are running kibana without https
#opensearch_security.cookie.secure: false
```

opensearch-security/config.yml

```yml
---

_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      openid_auth_domain:
        description: "Authenticate via MSI IDP OIDC"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: "email"
            roles_key: "https://myoicdhost/groups"
            openid_connect_url: "https://myoicdhost/.well-known/openid-configuration"
        authentication_backend:
          type: noop
    authz:

```
