### ISSUE TITLE
[FEATURE] Migrate Plugin install into an GitHub action

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2207]
**Is your feature request related to a problem?**
The plugin-install workflow user to separate paths to configure and run OpenSearch from the min build.  This would be really useful if it was reusable for this codebase as well as others.  Being that we are thinking more multiplatform this is also an opportunity where we should could invest in combining these workflows.

**What solution would you like?**
In the `plugin-install` workflow the there all the downloading, configuring, starting of OpenSearch would be replaced with a step like the following:

```yml
   - id: start-opensearch
     uses: uses: ./.github/actions/start-opensearch
     with:
         platform: ${{ matrix.platform }}
         opensearch-version: 3.0.0
         plugin-zip-path: ./security-dashboards-plugin.zip
         plugin-start-script: plugins/opensearch-security/tools/install_demo_configuration.sh
```

This would the be reusable for workflows within this Security codebase, but also for https://github.com/opensearch-project/security-dashboards-plugin/issues/1171 where this kind of workflow would simplify the extra work needed

**Do you have any additional context?**
Started a prototype with https://github.com/peternied/security/commit/1b880f4797c60ee4ba60598e548cbdd28c16426d
