### ISSUE TITLE
[Question] Requirements for plugin onboarding

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/security#2256]
When a plugin included in distribution onboards a new API, are there any requirements/expectations it has to fulfill with respect to security. 

For instance, is it a requirement to follow https://github.com/opensearch-project/security#onboarding-new-apis and set up roles for the plugin?

If there are no requirements/expectations, should there be?

**Comment by peternied** [comment]
When a user attempts to make an API call with security enable the task name, such as `cluster:admin/plugins/replication/autofollow/update` are checked for permissions.  If the user does not have this permissions grant to them the request will be blocked.

If a new API is added it will automatically be blocked by the security plugins default configuration.  Many plugins should document how to add security [1], but this doesn't help for the out of the box scenarios.  Inside this repository there are the 'defaults' for action groups, roles, role mappings.  By making a modification in these files [2] the permission could be available by default depending on these assignments.

There are no 'hard requirements' as the Security plugin can work with plugins that are not included in the distribution.  However following common practice for the OpenSearch-Project should be in alignment to some degree, engage with @shanilpa @jimishs can help dig into the scenario and provide recommendations.

If you had an example of your API and how you'd like it to work we could dig in deeper.

----

@cwillum this would be good area to beef up our documentation for 'If you are plugin how do you work with the Security Plugin's access control system', maybe you could help clarify in our readme documentation

[1] https://opensearch.org/docs/latest/replication-plugin/permissions/
[2] https://github.com/opensearch-project/security/tree/main/src/main/resources/static_config

**Comment by jmazanec15** [comment]
> If you had an example of your API and how you'd like it to work we could dig in deeper.

Question is more general - I am not asking about specific APIs.

> There are no 'hard requirements' as the Security plugin can work with plugins that are not included in the distribution. However following common practice for the OpenSearch-Project should be in alignment to some degree, 

Right, I am asking more about alignment amongst plugins in the distribution. I see a lot of plugins have already added roles here: https://github.com/opensearch-project/security/blob/main/config/roles.yml - I am wondering if this should be a standardization - maybe more of a question for @jimishs and @shanilpa. Maybe put another way, when should a plugin add a role to security plugin for their APIs?

**Comment by cwperks** [comment]
Hey @jmazanec15, this is a good question. I am now seeing instances where roles reference actions that are not contained in `security-dashboards-plugin` [here](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/configuration/constants.tsx), which means that a user is not able to create a custom role that permits the individual action.

See example [role](https://github.com/opensearch-project/security/blob/main/config/roles.yml#L260-L270) in the latest 2.4.0 RC which has a list of actions that have not yet been added to `security-dashboards-plugin`'s list: 

```
security_analytics_read_access:
  reserved: true
  cluster_permissions:
    - 'cluster:admin/opensearch/securityanalytics/alerts/get'
    - 'cluster:admin/opensearch/securityanalytics/detector/get'
    - 'cluster:admin/opensearch/securityanalytics/detector/search'
    - 'cluster:admin/opensearch/securityanalytics/findings/get'
    - 'cluster:admin/opensearch/securityanalytics/mapping/get'
    - 'cluster:admin/opensearch/securityanalytics/mapping/view/get'
    - 'cluster:admin/opensearch/securityanalytics/rule/get'
    - 'cluster:admin/opensearch/securityanalytics/rule/search'
```

I can see the role in OSD and map users, but I cannot create a custom role and assign the actions individually:

![Screen Shot 2022-11-11 at 10 40 49 AM](https://user-images.githubusercontent.com/17432265/201374553-15a63ba0-2996-452f-88ad-971541d5c66b.png)

Not in the dropdown:

![Screen Shot 2022-11-11 at 10 42 09 AM](https://user-images.githubusercontent.com/17432265/201374880-28793c38-87eb-4e63-adc8-e08a973b7467.png)

I'm not sure if this is desired behavior, but it is confusing that we display the action when looking at the reserved role but the same action is not assignable when creating a custom role.
