### ISSUE TITLE
[BUG] LDAP fails when the `security.ssl.transport.truststore_filepath` is missing

### ISSUE THREAD

**Issue by vaskosmihaylov** [opensearch-project/security#2548]
**What is the bug?**
This is a continuation of the issue [1866](https://github.com/opensearch-project/security/issues/1866). The LDAP authentication process fails when the `security.ssl.transport.truststore_filepath` is missing from the `opensearch.yml` file, leading to an unresolved bug from a previous issue. The steps to reproduce the bug are documented in the Opensearch forum thread, along with the host/environment details.

**How can one reproduce the bug?**

All the steps and config files are published in https://forum.opensearch.org/t/empty-file-path-for-plugins-security-ssl-transport-truststore-filepath-ldap-authentication/12991 thread. 

**What is the expected behavior?**
The LDAP authentication process should function as expected when the `security.ssl.transport.truststore_filepath` is missing from the `opensearch.yml` file, and the `pemtrustedcas_filepath:` is included in the `config.yml` file

**What is your host/environment?**
All the information is provided in the Opesearch forum thread 

**Do you have any screenshots?**

**Do you have any additional context?**
It appears that the Java code responsible for the logic of how the CA certificates are read is located at [this location](https://github.com/opensearch-project/security/blob/main/src/main/java/com/amazon/dlic/util/SettingsBasedSSLConfigurator.java#L181). We are unsure if the documentation is incorrect, as the `security.ssl.transport.truststore_filepath` option is listed as optional, while it appears to be required for authorization. We are also considering the possibility of changing the logic for searching the IdP RootCA certificate

**Comment by peternied** [comment]
[Triage] Thanks for filing @vaskosmihaylov looks like have an issue here that should be investigated.  Additionally thanks for following up on the forums and back here.

**Comment by pabloalcantara** [comment]
Any news on this problem?
I need to enable SSL for LDAP, and this same problem is happening with me.
Withou SSL, the ldap authentication works perfectly, but when enabling to use LDAPS, this same error happens.

**Comment by digitalray** [comment]
We are experiencing the same issue. Is there a plan to take a look at this?

**Comment by pabloalcantara** [comment]
Does exist any way to counturn this problem?

**Comment by gdeleon23** [comment]
Hi! Same problem!  any news?

**Comment by SeanathanVT** [comment]
Same issue. Pretty frustrating. :(

**Comment by mooneym17** [comment]
same problem when using PEM certs.
 [WARN ][c.a.d.a.l.b.LDAPAuthorizationBackend] [x] Unable to connect to ldapserver x.x.x.x:636 due to OpenSearchException[Empty file path for plugins.security.ssl.transport.truststore_filepath]. Try next.

**Comment by frale98** [comment]
same problem for us, must use secure layer to access LDAP server.

**Comment by gza** [comment]
I have found a start of explanation and a workaround.

Note: I use docker-compose setup

First reflex, _You want this `plugins.security.ssl.transport.truststore_filepath`, I will give it to you..._
So I tried to set `plugins.security.ssl.transport.truststore_filepath: /etc/pki/java/cacerts` but this leads to `java.security.AccessControlException: access denied`

It looks like there is no default truststore or a java policy blocks the access to it.

What worked is :

- to create a copy of `/etc/pki/java/cacerts` into `config/truststore.jks`
  - with docker
    - mount an empty file
    - from inside the container :  `cat /etc/pki/java/cacerts > config/truststore.jks`
- set `plugins.security.ssl.transport.truststore_filepath: truststore.jks`

Question: is it possible that setting `plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem` like doc says is the cause ? Maybe this replace a default CA certs file with all Certificates Authorities by only the local one

Anyway, my setup works with local certs and access to LDAP over TLS

**Comment by prabhask5** [comment]
@peternied @cwperks @scrawfor99 The docs now show this setting as required, does that mean this issue isn't relevant anymore, or is this a temporary fix and this option should be optional in the code? https://opensearch.org/docs/latest/security/configuration/tls/#keystore-and-truststore-files

**Comment by gza** [comment]
@prabhask5, I do think opensearch should have (or keep if the `pemtrustedcas_filepath` with local CA broke it) an active truststore with well known CAs by default (like any software in the world).

I don't know in details how to achieve that, but Java security settings should allow using system's cacerts (jdk one if any) & it should be the default value for `security.ssl.transport.truststore_filepath`

What I was obliged to do is a hack than a solution.

**Comment by cwperks** [comment]
@vaskosmihaylov I just tried to reproduce this error. I was able to reproduce the error from the OP description by setting `enable_ssl: true` and not configuring `pemtrustedcas_filepath` on the LDAP config, but after some trial and error I was able to get it to work. 

One this I noticed is that on this [forum post](https://forum.opensearch.org/t/empty-file-path-for-plugins-security-ssl-transport-truststore-filepath-ldap-authentication/12991?u=cwperks), the `pemtrustedcas_filepath` was only configured in the `ldap authenticator` (`authc:` section) and was not also configured in the `ldap authorizer` (`authz:` section). After configuring this setting twice (in both `authc:` and `authz:`) I was able to login. 

```
authc:
  ldap_auth:
    order: 1
    description: "Authenticate using LDAP"
    http_enabled: true
    transport_enabled: false
    http_authenticator:
      type: basic
      challenge: false
    authentication_backend:
      type: ldap
      config:
        pemtrustedcas_filepath: /usr/share/opensearch/config/root-ca.pem
        enable_ssl: true
        enable_start_tls: false
        enable_ssl_client_auth: false
        verify_hostnames: false
        hosts:
        - openldap:636
        bind_dn: cn=readonly,dc=example,dc=org
        password: changethistoo
        userbase: ou=People,dc=example,dc=org
        usersearch: (cn={0})
        username_attribute: cn

authz:
  ldap_roles:
    description: "Authorize using LDAP"
    http_enabled: true
    transport_enabled: false
    authorization_backend:
      type: ldap
      config:
        pemtrustedcas_filepath: /usr/share/opensearch/config/root-ca.pem
        enable_ssl: true
        enable_start_tls: false
        enable_ssl_client_auth: false
        verify_hostnames: true
        hosts:
        - openldap:636
        bind_dn: cn=readonly,dc=example,dc=org
        password: changethistoo
        userbase: ou=People,dc=example,dc=org
        usersearch: (cn={0})
        username_attribute: cn
        skip_users:
          - admin
          - kibanaserver
        rolebase: ou=Groups,dc=example,dc=org
        rolesearch: (uniqueMember={0})
        userroleattribute: null
        userrolename: disabled
        rolename: cn
        resolve_nested_roles: false
```
