### ISSUE TITLE
Update SecurityIndexAccessEvaluator to support new permission

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2553]

**Comment by samuelcostae** [comment]
@peternied  @scrawfor99  Sorry if the answer is obvious, but I have a question, each Extension will have it's own index? or is it only one index called "system_index"  that will contain info for all extensions? And Piggybacking on that, each extension would have it is own User and Role?

**Comment by peternied** [comment]
Additional background on system indexes configuration / security plugin interaction https://opensearch.org/docs/1.3/security/configuration/system-indexes/

Plugins implement the `SystemIndexPlugin` interface when they can describe N system indexes, [[link]](https://github.com/opensearch-project/OpenSearch/blob/c334bbde881c61e66b7b4768e2d43455f1c827d9/server/src/main/java/org/opensearch/plugins/SystemIndexPlugin.java#L41).  Extensions will do the same (but that is out of scope for this task).

Check out how different plugins use them by searching through the org [[search results]](https://github.com/search?q=org%3Aopensearch-project+SystemIndexPlugin&type=code).

**Comment by samuelcostae** [comment]
Hi!

"The new permissions allows for read and write operations on the permitted index(es)"

So a user mapped to the following role:

```
myExtensionRole:
  description: "Extension Role"
  cluster_permissions:
    - '*'
  index_permissions:
    - index_patterns:
        - '.myExtensionIndex'
      allowed_actions:
        - "system:admin/system_index"
```

Should be able to read/write  without any of the existing  allowed actions ? (e.g.  "indices:admin/get" )

Cause i was thinking, couldn't just block the access if it is trying to access and extension index without the new permission and if it has the new permission, proceed with the remaining existing permission checks?

**Comment by samuelcostae** [comment]
I created a draft PR: https://github.com/opensearch-project/security/pull/2681  

Here are some scenarios:

Given a index called 'system_index_b' configured as a 'system index'
The role below would be able to access system_index_b

```
extensions_role_b:
  description: "Limited ExtensionsRole"
  cluster_permissions:
    - '*'
  index_permissions:
    - index_patterns:
        - 'system_index_b'
      allowed_actions:
        - '*'
        - 'system:admin/system_index'
```

The role below would not be able to access system_index_b
```
extensions_role_c:
  description: "Limited ExtensionsRole"
  cluster_permissions:
    - '*'
  index_permissions:
    - index_patterns:
        - 'system_index_c'
      allowed_actions:
        - '*'
        - 'system:admin/system_index'
```

The role below would not be able to access system_index_b
```
all_access_role:
  description: "Limited ExtensionsRole"
  cluster_permissions:
    - '*'
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - '*'
```

Is that in the right direction?


@cwperks  ``` I'm not sure if it makes sense to introduce an action name that can be assigned in a role, without tying it to an actual action in OpenSearch. system:admin/system_index should correspond to the name of a transport action in OpenSearch.
```

Could you please expand on that?  

Thanks

**Comment by cwperks** [comment]
Hi @samuelcostae, thank you for opening a draft PR! The general problem for extensions that needs to be solved is how to ensure that an extension can write to a set of indices that it reserves and that any other user (including the admin with `all_access` role) cannot interact with those indices since the extension relies on those indices to function properly. In the plugin architecture, plugins have the ability to meddle with other indices but since plugins are inherently trusted its assumed that they won't. Good intentions are great, but with security there needs to be assurances that the extension won't cease to operate normally because an admin inadvertently deleted an index that it relies on to run.

What's proposed here is one way to go about making system indices assignable via a role, but IMO the protection is not strong enough and breaks with convention. Any action name that you see in a roles definition: i.e.

```
cluster_permissions:
    - 'cluster:action/name/1'
    - 'cluster:action/name/2'
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - 'indices:action/name/1'
        - 'indices:action/name/2'
```

Are all connected to a TransportAction. See SearchAction (`indices:data/read/search`) for an example: https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/search/SearchAction.java#L45

IMO what I would like to see for system accounts is a new type of account different from a regular user. This type of account would be called a `Service Account` and that account could be associated with an external service (re: extension). If that extension reserves indices (similar to plugins that extension SystemIndexPlugin), then the service account should be permitted in some way to interact with the indices that its requesting to reserve. For Anomaly Detection, that would be the set of index patterns: `[".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state"]`

-----

One general question I have for the proposed solution here, would `all_access` be given this new permission `system:admin/system_index` or would there be some way to exclude this from a user with the `all_access` role?

There was another PR that introduced new permissions, but added logic to prevent them from being assigned if a user entered `*` for all of the cluster_permissions or index_permissions.

**Comment by samuelcostae** [comment]
_One general question I have for the proposed solution here, would all_access be given this new permission system:admin/system_index or would there be some way to exclude this from a user with the all_access role?_

@cwperks  In the implementation in the draft PR, and considering all_access user exemplified above, the user not able to access/modify the extension's system indexes, even with the "*" permission

**Comment by cwperks** [comment]
@samuelcostae Got it, sorry I have not had a chance to review the Draft PR just yet. I will get around to that today. I think this proposal could work, but I do have some concerns about a roles definition like:

```
all_system_indices:
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - 'system:admin/system_index'
```

That would be a powerful role and what would prevent an admin from assigning themselves to this role?
