### ISSUE TITLE
[Question] How do administrators control what extensions can do?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2587]

**Comment by peternied** [comment]
@scrawfor99 Love to get some initial thoughts

**Comment by cwperks** [comment]
@peternied I'd like to add my 2 cents on this too. 

I'll try to summarize succinctly in 3 parts:

1. For installation purposes I think we should be broad. Signal to the cluster admin what kind of extension they are installing. 

For AD that means: 

- ActionExtension - it will extend OpenSearch by adding new endpoints
- ScriptExtension
- JobSchedulerExtension

We can document precisely what it means for an extension to be any one of these types and when UX is developed for installation this could be a prompt on installation.

Using the `./bin/opensearch-plugin install` tool you get prompted to accept the plugin's policy on installation. This prompt would be analogous and upfront explain to the cluster admin how the extension would like to extend OpenSearch.

```
➜  opensearch-3.0.0-SNAPSHOT ./bin/opensearch-plugin install file:/Users/cwperx/Desktop/distributions/opensearch-security-3.0.0.0-SNAPSHOT.zip
-> Installing file:/Users/cwperx/Desktop/distributions/opensearch-security-3.0.0.0-SNAPSHOT.zip
-> Downloading file:/Users/cwperx/Desktop/distributions/opensearch-security-3.0.0.0-SNAPSHOT.zip
[=================================================] 100%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission /proc/sys/net/core/somaxconn#plus read
* java.lang.RuntimePermission accessClassInPackage.com.sun.jndi.*
* java.lang.RuntimePermission accessClassInPackage.sun.misc
* java.lang.RuntimePermission accessClassInPackage.sun.nio.ch
* java.lang.RuntimePermission accessClassInPackage.sun.security.x509
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission accessUserInformation
* java.lang.RuntimePermission createClassLoader
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.lang.RuntimePermission shutdownHooks
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.NetPermission getNetworkInformation
* java.net.NetPermission getProxySelector
* java.net.SocketPermission * connect,accept,resolve
* java.security.SecurityPermission getProperty.ssl.KeyManagerFactory.algorithm
* java.security.SecurityPermission insertProvider.BC
* java.security.SecurityPermission org.apache.xml.security.register
* java.security.SecurityPermission putProviderProperty.BC
* java.security.SecurityPermission setProperty.ocsp.enable
* java.util.PropertyPermission * read,write
* java.util.PropertyPermission org.apache.xml.security.ignoreLineBreaks write
* javax.security.auth.AuthPermission doAs
* javax.security.auth.AuthPermission modifyPrivateCredentials
* javax.security.auth.kerberos.ServicePermission * accept
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]
```

3. There should be a policy that governs how requests coming from an extension can interact with opensearch - it looks like a role, smells like a role and can be implemented like a role, but this is a policy that governs requests coming from an extension and should not be mappable to users.

```
extension/ad:
    extension_policy: true # Should not be mapped to a user
    reserved: true
    cluster_permissions:
        - 'cluster_monitor'
    index_permissions:
        - index_patterns:
            - 'logs-*'
        allowed_actions:
            - 'indices_monitor'
            - 'indices:admin/aliases/get'
            - 'indices:admin/mappings/get'
```

4. The service account created for an extension (assuming the extensions needs one - not all do) can have a token issued for it and that token can have a single role associated with it. For most cases, it should be narrowly targeting the system index reserved by an extension so it can interact with it.

```
extension/ad_svc:
    reserved: true
    index_permissions:
        - index_patterns:
            - '.opendistro-anomaly-results*'
            - '.opendistro-anomaly-detector*'
            - '.opendistro-anomaly-checkpoints'
            - '.opendistro-anomaly-detection-state'
        allowed_actions:
            - 'indices_all'
```

**Comment by peternied** [comment]
@cwperks I would like to separate fine-grain access control from this discussion, it's important **and** terribly complex.  Supporting these scenarios is a better fit for service accounts and the tools associated with them.

- https://github.com/opensearch-project/security/issues/2597

I think I might be missing a concern of yours could you call it out specifically or what is the user scenario that is missed or incomplete?  Extensions honoring security posture are new we have considerable flexibility in what we implement.

**Comment by cwperks** [comment]
@peternied Yes, let me try to explain more in detail. I really would like to dig into this further so hear me out. On a high-level, I think if we define these policies (the policy that governs how requests coming from a service on behalf of a user can interact with opensearch) like role that there will be a great deal of code re-use and it would also deliver a high bar of security and flexibility right off the bat. In the comment above I described a convention for naming a policy per extension/service, I now think that's too inflexible so I have another proposal but before I introduce that let's clearly state the problem.

#### Problem

The security plugin will now be issuing tokens on behalf of a user to give to an external service (I will be using extension/service interchangeably. Service refers to something more generic than an extension. An extension is a service.) When a service makes a request on behalf of the user utilizing this token it must be authorized by the security plugin before the request is executed.

How is this request authorized?

For some background assume the payload of token looks like:

```
# Payload
{
  "iss": "<cluster_name>",
  "iat":1676908684,
  "exp":1676908744,
  "sub":"<principal_identifier_token>",
  "r":"<encrypted_mapped_roles>", # r for roles
  "br": "<encrypted_backend_roles>", # br for backend_roles
  "aud": "extension/{extensionUniqueId}" // The identifier of the service this token is issued for
}
```

When authorizing this request, privilege evaluation will be done at 2 gates:

1. **Service gate** - In this gate privilege evaluation is performed to ensure that the request on-behalf-of a user from the specific service is permitted
2. **User gate** - In this gate, the user's privileges are evaluated to ensure the user can perform the action

#### Proposal: Map service + user to role(s) [policy] that specify what a request on behalf of the user from the service can do

For this proposal, I want you to imagine the `all_access` role renamed. For this proposal think of the `all_access` role as `act_as_original_user`

```
# roles.yml

act_as_original_user:
  reserved: true
  description: "This policy permits any request from a service on-behalf-of a user. In effect, the service is allowed to act as if it were the user."
  cluster_permissions:
    - "*"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "*"
  extension_permissions: # Yes, this permits called other extensions too
    - "*"
``` 

This policy could be defined in the `roles` section of the security plugin and I believe we can also use `roles_mappings` to map this to a user in the following way.

```
# roles_mapping.yml

act_as_original_user:
  reserved: false
  description: "Maps <service_id> extension to act_as_original_user"
  services_mappings:
   <service_id>:
      users: 
        - "*"
```

Read this as map all users of the <service_id> extension can be mapped to the `act_as_original_user` role (policy) that will be utilized when evaluating privileges at the service gate.

**Zooming in on the service gate**

The service gate is the first gate the request must get through to be considered authorized. At the service gate the request must be resolved to a set of roles (policies) that can be checked to see if the request is permitted.

Imagine a function:

```
Set<String> mappedPolicies = mapPolicies(user, serviceId)
```

This function goes through the `roles_mapping` as defined above and resolves to `act_as_original_user`

If this set is empty we will block the request - some policy needs to be resolved to.

If we can resolve to a set of policies then let's re-use the `PrivilegesEvaluator` using this set of roles and if granted, proceed to the User gate.

#### The term roles is overloaded

The term roles is overloaded in the security plugin. To be clear, when I speak of roles there are 3 concepts to consider:

1. `role` - I think of these as internal roles - these are the roles defined in `roles.yml`
2. `backend_roles` - Backend roles are typically extracted from another IdP, but not necessarily. They can be assigned in OSD as a grab bag list of strings associated with a user.
3. `mappedRoles` - The mapped roles are the result of the roles resolution process which in effect maps backend roles to internal roles. Roles can also be mapped by the caller's IP Address/Hostname.

The hostname mapping I take a bit of an issue with because I think its more apt to conceptually think about it as a policy. An IP Address gets mapped to a role so a set of privileges can be evaluated, but IMO its better to think about the roles as a policy that governs how requests from that IP Address can interact with the cluster.

#### Comments on Service Account / Service Account Token

A service account token is used for the extension to interact with the OpenSearch cluster as itself and not on behalf of a user.

My thoughts is that absent of UX, we should have a cluster admin define if they want a service account + a token through `extensions/extensions.yml`. Since this file is controlled by the cluster admin, I think we should assume that any setup in this file has the explicit permission of the cluster admin so we should take it as is. 

In the special case of an extension requesting to reserve indices we may wish to automatically provide a token scoped to those reserved indices.

Take for example `ad_settings.yml` - the settings file for AD extension:

```
extensionName: anomaly-detection
hostAddress: 127.0.0.1
hostPort: 4532
opensearchAddress: 127.0.0.1
opensearchPort: 9200
reservedIndices: [".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state"]
```

Inside of `extensions/extensions.yml` the cluster admin can grant AD extension reserved indices via a setting like:

```
extensions:
  - name: anomaly-detection
    uniqueId: ad
    hostAddress: '127.0.0.1'
    port: '4532'
    version: '1.0'
    opensearchVersion: '3.0.0'
    minimumCompatibleVersion: '3.0.0'
    allowReservedIndices: true
```

Since this extension is requesting to reserve indices and the administrator has given permissions, we should automatically create a service account and a service account token scoped to those indices and send it to the extension.

**Question: What if the extensions wants reserved indices and other permissions?**

Additional service account permissions should live in `extensions/extensions.yml` which is owned by the cluster admin to ensure the cluster admin is the one that explicitly grants the permissions. An extension developer who desires their extension to have the ability to do more on its own must provide installation instructions to the cluster admin to tell them what to add in `extensions.yml`.

This is contrived, but imagine that there is an AD extension that wants to act as a daemon on `logs-*`. The developer of such extension would instruct the cluster admin to add `serviceAccountPermissions` inside the extensions configuration in `extensions.yml`.

```
# ad-settings.yml

extensionName: anomaly-detection
hostAddress: 127.0.0.1
hostPort: 4532
opensearchAddress: 127.0.0.1
opensearchPort: 9200
reservedIndices: [".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state"]
```

and on the cluster admin side in `extensions.yml`

```
# Read this as the extensions is granted permission to read from logs-* as a daemon - on its own

extensions:
  - name: anomaly-detection
    uniqueId: ad
    hostAddress: '127.0.0.1'
    port: '4532'
    version: '1.0'
    opensearchVersion: '3.0.0'
    minimumCompatibleVersion: '3.0.0'
    allowReservedIndices: true
    serviceAccountPermissions:
      index_permissions:
        - index_patterns:
            - 'logs-*'
          allowed_actions:
            - 'read'
```

In this case we could either create two roles associated with the service account, 1 scoped to the reserved indices and 1 and with the permissions defined in `serviceAccountPermissions` or we could combine them to create a single role. Maybe 2 roles makes sense here to make it straightforward to implement. 

Please let me know your thoughts and I'd really love to dive in further because I'm becoming pretty convinced that this is both a good design and maximizes code re-use.

**Comment by peternied** [comment]
@cwperks I like the notion of **service gate** and **user gate**.  I think that this is an example of something that is specific to extensions that I would call Application Scope, typically dropping the word application.  I also think that how service gates are implement need not be the same as user gates - I am going to advocate they are implemented completely separately.

Look at these scopes from Slack [1] like `channels.write` `files.read`, `reminders.write`, ...  they cover all the features that can be interacted with a slack instance and are readable.  I would rather make a clear contract with administrators that are limited, rather than give them the flexibility / complexity of the Security Plugin permissions.

I've been tweaking the description, and I'll be continuing to make changes, thanks for the feedback.

- [1] https://api.slack.com/legacy/oauth-scopes

**Comment by cwperks** [comment]
@peternied If we could try to enumerate a list of initial scopes I think that would facilitate the conversation greatly. Would it be possible to have a scope version of the following portion of a roles definition?

```
index_permissions:
    - index_patterns:
        - 'logs-*'
      allowed_actions:
        - 'read'
```

I was aiming for code re-use with the proposal above, but I see how there can be some difficulty in devising what the policy definition for a service could be. 

There could be a catalog of policies for common-cases similar to the reserved roles that are automatically created today:

```
act_as_original_user:
  extension_policy: true
  reserved: true
  description: "This policy permits any request from a service on-behalf-of a user. In effect, the service is allowed to act as if it were the user."
  cluster_permissions:
    - "*"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "*"
  extension_permissions: # Yes, this permits calls to other extensions too
    - "*"

indices_readonly:
  extension_policy: true
  reserved: true
  description: "This policy permits any read requests to OpenSearch indices from a service acting on behalf of a user"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "read"
```
