### ISSUE TITLE
[Extension] Authentication Backend for JIT Token Validation

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security#2619]
### Problem:
To accomplish the objective of enabling extensions to act on behalf of a user, we have devised a just-in-time (JIT) Token to manage incoming request authentication. This JIT Token will be transmitted to the extension and subsequently returned to the security plugin for privilege validation concerning both the user and the extension. Consequently, it is necessary to develop an authentication backend to efficiently handle these validation processes.

### Design
Here is a graph of how user requests processed through the security-extension feature _[graph1]_:
![Extensions for security](https://user-images.githubusercontent.com/109499885/225071058-492bff0e-93fa-4ff6-8229-e85ab6845c95.jpg)
If we zoom up to step 4. & 5 in _[graph1]_ then we get _[graph2]_ as following:
![OpenSearch_JIT_Extension drawio](https://user-images.githubusercontent.com/109499885/229668480-cc551278-6e17-4dbd-b937-8ef6f09f472d.png)
This graph shows that during the creation of the JIT Token, the user's roles will be encrypted (see: #2620 ) and combined with other claims. Subsequently, this JIT Token will be sent to the extension for further processing. 

Once the extension sends back this token to security plugin, which is step 6 in _[graph1]_ then we get _[graph3]_ as following:
![OpenSearch_JIT_Extension drawio (1)](https://user-images.githubusercontent.com/109499885/229669028-a30d5d1c-8c4b-4da4-bd58-3d6edb2ec9fd.png)
Once the security plugin receives the JIT Token back, it will be forwarded into the authentication backend. The following tasks will be initiated: 
* Decrypt roles / backend_roles fields inside of the JIT Token
* Two validations will happen: 
    * Validation of extensions privilege - Service Gate (1st gate and we process to the next gate after the validation)
        * Similar to user roles this field is called governing policies, and the major difference is that you cannot map those policies to users. We need to do is to compare these policies with the specific actions from the request.
        * If the Service Gate validation fails, it will directly abort the target action, and it will not process to the User Gate.
    * Validation of user privilege - User Gate (2nd gate)
        * Decrypt `roles` / `backend_role`
        * Validate the privileges by using the roles concepts (like current role concept)

### Appendix
[WIP] I will put link this section to some of the issues with more concepts of `roles.yml`.

**Comment by RyanL1997** [comment]
Hi @cwperks, I have transferred the doc into this issue. Feel free to leave some thoughts.

**Comment by cwperks** [comment]
Hi @RyanL1997, thank you for adding the diagrams for this issue! These are good visualizations for what we've been discussing about creating the tokens in core/security plugin to pass to an extension and then what happens on the core/security plugin side of things if the extension uses the token to make a request to the cluster. Some of the diagrams on here may be subject to change based on the discussion on this issue: https://github.com/opensearch-project/security/issues/2587

This comment in particular (https://github.com/opensearch-project/security/issues/2587#issuecomment-1493067740) talks about how the mapping would work from the extension + user -> set of role/policies that would be used for privilege evaluation.

In short, the idea is to add a new `services_mappings` sub-section on a `roles_mapping` to map an extension + user to a set of role/policies to check at the service gate:

```
# All users of service <service_id> are mapped to act_an_original_user
act_as_original_user:
  reserved: false
  description: "Maps <service_id> extension to act_as_original_user"
  services_mappings:
   <service_id>:
      users: 
        - "*"
```

For the diagrams, I would update anywhere you show user roles to a different hypothetical example (userA mapped to role1, role2, role3 - you can keep these abstracted, they represent any roles the user is mapped to)

It looks like the set of permissions used in the example was a set of permissions for AD service account:

```
extension/ad_svc:
    reserved: true
    index_permissions:
        - index_patterns:
            - '.opendistro-anomaly-results*'
            - '.opendistro-anomaly-detector*'
            - '.opendistro-anomaly-checkpoints'
            - '.opendistro-anomaly-detection-state'
        allowed_actions:
            - 'indices_all'
```

Service account / service account token is different than the just-in-time tokens that this issue discusses because for a service account token, the extension is not acting on behalf of another user. In this case, the extension is interacting with the cluster using its service account token and privilege evaluation would be the same as normal user privilege evaluation where there is no service gate.
