### ISSUE TITLE
Authorizing User against requested extension endpoint

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#2622]

**Comment by scrawfor99** [comment]
[Triage] This is part of the Extensions project.

**Comment by samuelcostae** [comment]
@scrawfor99 @cwperks Hi, I was working on this, but then while looking for more info I came across this branch/PR which at first sight seem to me to be aiming at the same thing.

Is that the case?

**Comment by cwperks** [comment]
Hi @samuelcostae, that PR is related but there are still items related to figure out. I was hoping to get extension TLS related changes merged earlier which helps with testing REST-layer authz since you can spin up an extension and an opensearch node with the security plugin installed and test the change end-to-end. Eventually, all of that manual testing will be automated where we can test an opensearch node with the security plugin installed operating with extensions.

Related to that PR there are 2 immediate follow-up problems to figure out:

1. https://github.com/opensearch-project/security/issues/2595 - This change is taking roles defined in the security plugin's `roles.yml` and instead sourcing them to the security index from an extension configuration file
2. The PR works to migrate any plugin that defines a `cluster:*` action, but does not work with `indices:*` such as:

```
index_management_full_access:
  reserved: true
  cluster_permissions:
    - "cluster:admin/opendistro/ism/*"
    - "cluster:admin/opendistro/rollup/*"
    - "cluster:admin/opendistro/transform/*"
    - "cluster:admin/opensearch/notifications/feature/publish"
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - 'indices:admin/opensearch/ism/*'
```

There also needs to be a way to permission based on index patterns that are supplied with a request too. This second item isn't captured in an issue yet, but I will create one for it on Monday.
