### ISSUE TITLE
[Extensions] Add support for `extension_dns` list in `extensions.yml` file

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#2730]
Similar to the setting `plugins.security.nodes_dn` which lets a cluster admin define the list of distinguished names that a node of the cluster can use to join the cluster with, extensions need an analogous mechanism. The distinguished name is extracted from the node's transport certificate and identifies a request as coming from a node (though not uniquely - nodes can connect with the same distinguished name and this is even done in the demo configuration!). 

This new setting will initially be static, though this needs to also be dynamic in future iterations similar to the `nodes_dn.yml` dynamic configuration file.

This setting can reside in the `extensions/extensions.yml` file like so:

```
extensions:
  - name: hello-world
    uniqueId: hw
    hostAddress: '127.0.0.1'
    port: '4532'
    version: '1.0'
    opensearchVersion: '3.0.0'
    minimumCompatibleVersion: '3.0.0'
    extension_dns:
      - 'CN=extension-01,OU=SECURITY,O=OPENSEARCH,L=BROOKLYN,ST=NEW YORK,C=US'
```
