### ISSUE TITLE
[Feature/Extensions] Supporting `cluster_permissions` nomenclature

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#2752]
Current security roles model uses `cluster_permissions` to evaluate Transport Layer actions. This is because the plugins run  in-process with OS cluster. 
With Extensions being out-of-process entities, they can request OS cluster only via REST APIs.
And so there is a need to authorize these requests at REST layer.

This issue covers authorizing REST request against the legacy and new `cluster_permissions` model.

E.g: For [hello-world sample extension](https://github.com/opensearch-project/opensearch-sdk-java/tree/main/src/main/java/org/opensearch/sdk/sample/helloworld), the endpoint `/hello` should succeed when either of the following roles are mapped to a user.

```yml
legacy_hw_greet:
  reserved: true
  cluster_permissions:
    - 'cluster:admin/opensearch/hw/greet'


extension_hw_greet:
  reserved: true
  cluster_permissions:
    - 'hw:greet'
```

This enables minimal effort for admin to enable use of extensions.

- [ ] Allow registering legacy transport actionName when registering a NamedRoute
