### ISSUE TITLE
OpenSearch Cluster OpenID Connect Authenticate with any Token with proper Role[BUG]

### ISSUE THREAD

**Issue by ramizraza504** [opensearch-project/security#2766]

**Comment by cwperks** [comment]
Hi @ramizraza504, thank you for the request to support required audience and issuer for OIDC backend. This gap with the JWT auth backend was recently identified separately and support is being added in this PR: https://github.com/opensearch-project/security/pull/2708. 

With the OIDC backend, if the auth backend can 1) verify the signature of the JWT that was issued on successful authentication in the external IdP, 2) extract the subject `subject_key` and 3) extract backend roles `roles_key`, then the user can be successfully authenticated with the OIDC backend. Full details of the backend can be found in the [HTTPJwtKeyByOpenIdConnectAuthenticator](https://github.com/opensearch-project/security/blob/main/src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticator.java).

I am renaming this ticket to reflect that this is a new feature of the OIDC backend to make it even more secure by adding a `required_issuer` and `required_audience` support (separate new config options). With the settings you would be able to setup an OIDC backend like this:

```
openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: groups
            openid_connect_url: http://host.docker.internal:8080/auth/realms/master/.well-known/openid-configuration
            required_issuer: keycloak
            required_audience: cluster_name
        authentication_backend:
          type: noop
```

**Comment by ramizraza504** [comment]
@cwperks Thanks for your response. When I was reviewing the code I did found that currently [https://github.com/opensearch-project/security/blob/main/src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java](url) being used by [https://github.com/opensearch-project/security/blob/main/src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticator.java](url) which only has subject and roles key option. Also I saw this new file [https://github.com/opensearch-project/security/blob/main/src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java](url) which has new fields audience and issuer . So is this the code being worked on the PR ? .

**Comment by cwperks** [comment]
Hi @ramizraza504, that's right. These fields are present into `HTTPJwtAuthenticator` (`authc:` configuration example here: https://opensearch.org/docs/2.7/security/configuration/configuration/#configure-jwts), but not on `HTTPJwtKeyByOpenIdConnectAuthenticator` which is the backend used for OIDC. With the OIDC backend, OpenSearch gets a token from an external identity provider compliant with OpenID Connect and on the first successful authentication the OIDC backend gives OpenSearch Dashboards an access token that it will use on subsequent requests until the token is expired. With the JWT backend you can have any system issue the JWTs as long as you configure the backend to have a key that can verify the tokens. 

The `required_issuer` and `required_audience` are being moved to `AbstractHTTPJwtAuthenticator` as part of that PR so that the options will be available for both OIDC and JWT backends.

**Comment by cwperks** [comment]
It actually may be possible, but its a hack-y workaround. You could take advantage of `order:` in the `authc:` section. 

In this setup the JWT authenticator would need to be configured with the same key that OIDC used to issue the JWT.

```
authc:
    jwt_auth_domain:
      http_enabled: true
      transport_enabled: true
      order: 0
      http_authenticator:
        type: jwt
        challenge: false
        config:
          signing_key: "base64 encoded key"
          jwt_header: "Authorization"
          jwt_url_parameter: null
          subject_key: null
          roles_key: null
          jwt_clock_skew_tolerance_seconds: 20
      authentication_backend:
        type: noop
    openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: groups
            openid_connect_url: http://host.docker.internal:8080/auth/realms/master/.well-known/openid-configuration
        authentication_backend:
          type: noop
```

`required_audience` and `required_issuer` will be officially supported for OIDC backend in 2.8.0 which has a target release date of June 6.
