### ISSUE TITLE
[BUG] Login with Microsoft Azure SSO doesn't detect existing SSO session in browser

### ISSUE THREAD

**Issue by K3ndu** [opensearch-project/security#2831]
**What is the bug?**
Every time when I log in to Opensearch Dashboards with Azure SSO, I have to type in username & password, do the MFA and all that stuff. It doesn't detect that I already have an active Microsoft Azure SSO session.

**How can one reproduce the bug?**
1. Go to Opensearch Dashboard
2. Click on Log in with single sign-on
Get prompted with Microsoft login.

**What is the expected behavior?**
Opensearch detects that I already have Microsoft SSO session active and login with those credentials.

**What is your host/environment?**
 - OS:Windows
 - Version 2.7.0
 - Plugins

Is this something that can be configured to work or it's something thats missing currently?

**Comment by scrawfor99** [comment]
[Triage] Hi @K3ndu, thank you for filing this issue. Could you provide additional information about how you have configured your cluster? For example, could you provide your yaml file and whether you are using SAML or OIDC etc.? Thank you again.

**Comment by K3ndu** [comment]
I'm using SAML

```
config:
  dynamic:
    kibana:
      multitenancy_enabled: false
      private_tenant_enabled: false
      #default_tenant: global tenant
      server_username: admin
      index: '.kibana'
    do_not_fail_on_forbidden: false
    http:
      anonymous_auth_enabled: false
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      saml_auth_domain:
        order: 1
        description: "Azure AD authentication"
        http_enabled: true
        transport_enabled: false
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: https://login.microsoftonline.com/xxxxxxxxxx-xxxxxxxxx-xxxxx/federationmetadata/2007-06/federationmetadata.xml?appid=xxxxxxxx-xxxxxxx-xxxxxx #SAML's metadata url, provided by your IdP
              entity_id: https://sts.windows.net/xxxxxxxxxxxxxx-xxxxxxxx-xxxxxxx/ #SAML's IdP entity ID, provided by your IdP
            sp:
              entity_id: opsrch-ad-sso
              forceAuthn: true
            kibana_url: https://opensearch-dashboards.example.net/
            roles_key: http://schemas.microsoft.com/ws/2008/06/identity/claims/groups
            exchange_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        authentication_backend:
          type: noop
```
