### ISSUE TITLE
[Question] Should request be pass through at Transport Layer once it is authorized at REST layer?

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#2867]
In the new model, we have moved authorization checks at REST layer. This alludes to a bigger question: "Should the REST authorized requests be passed through at Transport Layer?" and it applies to plugins that require Transport Layer interaction.

This question came up when trying to test an actual plugin endpoint by modifying it use the new route naming model.

Possible Answers:

1. YES. The request can be marked at "already authorized" and can be marked as pass through by adding a config constant in thread context. (This will happen only for `cluster_permissions`. Everything )
By doing so, we eliminate the need to double check permissions. This will allow supporting new permission model, without making any modifications at Transport layer.

2. NO. The request should still be evaluated at Transport Layer, even though it was marked as already authorized. This will act as a safety net.
Implementing this requires adding an extra check for permission evaluation at Transport Layer that checks for these new permissions in the list of `cluster_permissions` defined. This may also slightly affect performance.

**Comment by DarshitChanpura** [comment]
@cwperks I know you had some thoughts on this. Feel free to edit the description and/or add comments here.

**Comment by cwperks** [comment]
IMO it should be since the request is authorized - there's no need to pass through 2 gates.

Let's say we support a new AD permission-ing scheme where the user can be permitted to use AD either through having a role with the corresponding transport action names or with a new NamedRoute scheme.

Anomaly Read Only role with transport action names:

```
anomaly_read_access_transport_layer_authz:
  reserved: true
  cluster_permissions:
    - 'cluster:admin/opendistro/ad/detector/info'
    - 'cluster:admin/opendistro/ad/detector/search'
    - 'cluster:admin/opendistro/ad/detectors/get'
    - 'cluster:admin/opendistro/ad/result/search'
    - 'cluster:admin/opendistro/ad/tasks/search'
    - 'cluster:admin/opendistro/ad/detector/validate'
    - 'cluster:admin/opendistro/ad/result/topAnomalies'
```

vs. the same role, but with a hypothetical new naming scheme:

```
anomaly_read_access_rest_layer_authz:
  reserved: true
  cluster_permissions:
    - 'ad:detector/info'
    - 'ad:detector/search'
    - 'ad:detectors/get'
    - 'ad:result/search'
    - 'ad:tasks/search'
    - 'ad:detector/validate'
    - 'ad:result/topAnomalies'
```

Either should work to allow a user to use AD. 

-----

I have been mulling over a problem about how to fallback to transport layer authz if rest layer authz fails and here's what I am currently thinking. If REST-layer authz fails I don't think it should fail the request, I think it should move onto transport layer authz to see if the user is permitted to perform the transport action(s) run by the REST handler.

REST Layer authz would be a convenient way for new plugin developers to provide authorization to their API endpoints without necessarily having a transport action.

For plugins that would like to convert to using a new naming scheme they still may want to support the old naming scheme as well so in effect a user either needs to have a cluster permission that matches the route name or a cluster permission that matches the transport action name.

-----

For the flow:

1. User has access to use API
  - User is mapped to `anomaly_read_access_rest_layer_authz`
  - User calls on `/_plugins/anomaly/detector/_search`
  - User passed authz check on REST layer
  - Transport layer authz check is skipped since user has access to the endpoint

2. User has access to the transport action
  - User is mapped to `anomaly_read_access_transport_layer_auth`
  - User calls on `/_plugins/anomaly/detector/_search`
  - User fails authz check on REST layer (do not fail early here)
  - Authz check on transport layer is still run since rest layer authz failed - if user passes then permission is granted
