### ISSUE TITLE
Clean up -x task exclusions in ci.yml

### ISSUE THREAD

**Issue by nibix** [opensearch-project/security#2913]
At the moment, ci.yml contains many gradle task invocations with long exclusion lists like this:

```
         build test -Dbuild.snapshot=false
          -x integrationTest
          -x spotlessCheck
          -x checkstyleMain
          -x checkstyleTest
          -x spotbugsMain
```

This is because the jacoco plugin enforces explicit incoming dependencies from all test tasks. This will however also cause the execution of these "through the backdoor" if only a single test task is supposed to be executed.

It would be nice if a solution could be found to avoid that.

See also the conversation in this PR: https://github.com/opensearch-project/security/pull/2861#discussion_r1236935754

**Comment by pawel-gudel-eliatra** [comment]
Right now in #2861 we have one task exclusion:

```YAML
    - name: Build and Test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          ${{ matrix.gradle_task }} -Dbuild.snapshot=false
          -x test
```
