### ISSUE TITLE
[BUG] Active Directory LDAP integration does not work

### ISSUE THREAD

**Issue by Demon-DK** [opensearch-project/security#2948]
**What is the bug?**
Active Directory LDAP integration does not work !

<br/>

**What is your host/environment?**
- OS: CentOS/Redhat 7.9
- OpenSearch Version: 2.8.0
- OpenSearch Security Version: 2.8.0.0

<br/>

**How can one reproduce the bug?**
First, configure AD integration part here `/usr/share/opensearch/config/opensearch-security/config.yml` like that:
```
config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      ..................
      ldap:
        order: 1
        description: "Authenticate via LDAP or Active Directory"
        http_enabled: true
        transport_enabled: true
        # ------------------------
        http_authenticator:
          type: basic
          challenge: false
        # ------------------------
        authentication_backend:
          type: ldap
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: false
            hosts:
            - <ldap_server>:389 
...
```

<br/>

Second, start the instance and try to make a basic check
`curl https://localhost:9200 -ku <ldap_user>:<ldap_password>`

<br/>

After that you will get in the log the following messages:
```
[2023-07-06T07:57:41,849][WARN ][c.a.d.a.l.b.LDAPAuthorizationBackend] [opensearch] Unable to connect to ldapserver <ldap_server>:636 due to OpenSearchException[Empty file path for plugins.security.ssl.transport.truststore_filepath]. Try next.
[2023-07-06T07:57:41,851][WARN ][o.o.s.a.BackendRegistry  ] [opensearch] Authentication finally failed for <ldap_user> from 127.0.0.1:19811
```

<br/>

The first bug is that despite of two parameters below in the config it tries to connect to LDAP server trough 636 port `Unable to connect to ldapserver <ldap_server>:636`
- `enable_ssl: false`
- `hosts: - <ldap_server>:389`

<br/>

The second bug is related to next message in the log 
`OpenSearchException[Empty file path for plugins.security.ssl.transport.truststore_filepath]`

<br/>

When you update you SSL\TLS configuration  to use keystore/trustedstore and thus to use `plugins.security.ssl.transport.truststore_filepath` option then you will met the issue is opened here
https://github.com/opensearch-project/security/issues/2934
