### ISSUE TITLE
Change opensearch default password 

### ISSUE THREAD

**Issue by ibrahimjelliti** [opensearch-project/security#2982]
I deployed opensearch on eks successful but i want to customize the default password which is now `admin:admin` i cant see property for that in the values.yaml reference.

**Comment by peterzhuamazon** [comment]
Hi @peternied wonder if this is something that Security Team needs to check on.
Thanks.

**Comment by peterzhuamazon** [comment]
Hi @peternied wonder if this is something that Security Team can help.
Thanks.

**Comment by prudhvigodithi** [comment]
Hey @ibrahimjelliti you can try something like this https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#custom-admin-user and then update the `internal_users.yml` secret.
```
python -c 'import bcrypt; print(bcrypt.hashpw("admin123".encode("utf-8"), bcrypt.gensalt(12, prefix=b"2a")).decode("utf-8"))'
```

**Comment by scrawfor99** [comment]
[Triage] Hi @ibrahimjelliti, thank you for filing this issue. For more assistance in configuring your cluster settings please visit the OpenSearch [forum](https://forum.opensearch.org/).

**Comment by ibrahimjelliti** [comment]
@prudhvigodithi I hash a password using the Python script, and I updated the admin user hash in helm values 
 After I upgrade the OpenSearch helm chart and attempt to log-in with admin:<CUSTOM_PASSWORD>, I always get 401 Unauthorized.
```
securityConfig:
  config:
    data:
      internal_users.yml: |-
        _meta:
          type: "internalusers"
          config_version: 2
        ## Internal users
        admin:
          hash: "$2a$12$t7S16S/Gz8onn9Bo31LlyeIrXWMJJlE0F2HaSkDv22hBylqyToPE6"
          reserved: true
          hidden: false
          backend_roles:
          - "admin"
          attributes: {}
          description: "Admin user"
          static: false
 ```

**Comment by prudhvigodithi** [comment]
@ibrahimjelliti have to tried terminating the OpenSearch pods (rolling restart)?

**Comment by ibrahimjelliti** [comment]
I rolled a new release with the `helm upgrade ... -f values.yml`
but I can try also with `rollout restart`

**Comment by ibrahimjelliti** [comment]
I find this while following the node logs, yet I can authenticate to the cluster endpoint with `admin:admin`
`{"type": "server", "timestamp": "2023-07-10T22:03:39,562Z", "level": "WARN", "component": "o.o.s.a.BackendRegistry", "cluster.name": "opensearch-cluster", "node.name": "opensearch-cluster-master-0", "message": "Authentication finally failed for admin from 172.16.4.145:52260", "cluster.uuid": "ybe8lbVIQfqVOuvUcFXCKA", "node.id": "sN04VXeURROEG9pLhKos3g"  }`

**Comment by smlx** [comment]
Please carefully read the documentation I linked in this comment: https://github.com/opensearch-project/security/issues/2982#issuecomment-1629504872

If the `.opendistro_security` index is already initialized, you need to run `securityadmin.sh` in order to load subsequent configuration file changes into the `.opendistro_security` index.

**Comment by davidlago** [comment]
Closing as it seems like there is no underlying issue. Like @scrawfor99 points out, the forum is a great place to get troubleshooting help, as it then becomes part of the knowledge base that others can use to fix similar problems.

**Comment by ashutoshanshu07** [comment]
Hello Folks,

I am trying to change admin password using internal_user.yml ways but still , nothing is happing .
Could you please help me @ibrahimjelliti @davidlago @prudhvigodithi @peterzhuamazon @aetter

github link - https://github.com/opensearch-project/helm-charts.git
my updated values.yaml files 

```yaml
securityConfig:
  enabled: true
  path: "/usr/share/opensearch/config/opensearch-security"
  actionGroupsSecret:
  configSecret:
  internalUsersSecret:
  rolesSecret:
  rolesMappingSecret:
  tenantsSecret:
  # The following option simplifies securityConfig by using a single secret and
  # specifying the config files as keys in the secret instead of creating
  # different secrets for for each config file.
  # Note that this is an alternative to the individual secret configuration
  # above and shouldn't be used if the above secrets are used.
  config:
    # There are multiple ways to define the configuration here:
    # * If you define anything under data, the chart will automatically create
    #   a secret and mount it. This is best option to choose if you want to override all the
    #   existing yml files at once.
    # * If you define securityConfigSecret, the chart will assume this secret is
    #   created externally and mount it. This is best option to choose if your intention is to
    #   only update a single yml file.
    # * It is an error to define both data and securityConfigSecret.
    securityConfigSecret: ""
    dataComplete: true
    data: 
      internal_users.yml: |-
        _meta:
          type: "internalusers"
          config_version: 2
          
        admin:
          hash: "$2y$12$XDdc42zlZ.DhOj44X5zT.OnSxjGj5v7MEUllUG1euFG3wDp/AUGy2"
          reserved: false
          backend_roles:
          - "admin"
          description: "Demo admin user"

        kibanaserver:
          hash: "$2y$12$XDdc42zlZ.DhOj44X5zT.OnSxjGj5v7MEUllUG1euFG3wDp/AUGy2"
          reserved: false
          description: "Demo OpenSearch Dashboards user"
```

Please Help
