### ISSUE TITLE
[FEATURE] Security plugin config entries should have a `created_at` and `updated_at` timestamp

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3079]
**Is your feature request related to a problem?**

Config entries in the security index such as users, roles and roles_mappings have no timestamps associated with them to indicate when the entry was created or when it was most recently modified. When investigating issues, its often helpful to have this contextual information to determine when a change was made to help locate more information about the change. In many frameworks like Ruby on Rails, these timestamps come as a convention to track any objects that get persisted.

Each entry in the security index (i.e. a user or a role) should have these timestamps on the entry. This entry would help a cluster admin identify when a particular user/role/role_mapping/etc. is created or last modified.

**What solution would you like?**

Add `created_at` and `updated_at` timestamps to config entries in the security index. 

#### Example
Each entry, such as this example for user has both of these values

```yml
admin:
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
  reserved: true
  backend_roles:
  - "admin"
  description: "Demo admin user"
  created_at: 2023‐08‐30T06:05:02Z
  updated_at 2023‐09‐01T08:09:03Z
```
