### ISSUE TITLE
`transport_enabled` setting on an auth domain and authorizer may be unnecessary after transport client removal 

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3191]
Since OpenSearch 2.0, support for the transport client has been removed. The transport client was removed from the security plugin in this PR: https://github.com/opensearch-project/security/pull/1701

My understanding of `transport_enabled` is that it is used to enable an auth domain for authentication on the transport layer. There is a separate setting called `http_enabled` to enable the auth domain on the REST layer. This setting also appears to be applicable to authorizers in the `authz` section.

Below is an example of a basic auth entry in the `authc:` section of the security plugin's `config.yml` file from the demo configuration:

```
basic_internal_auth_domain:
    description: "Authenticate via HTTP Basic against internal users database"
    http_enabled: true
    transport_enabled: true
    order: 4
    http_authenticator:
      type: basic
      challenge: true
    authentication_backend:
      type: intern
```

The `transport_enabled` setting may not be needed here after the TransportClient's removal.

First: Determine if it is safe to remove values from settings. 
Second: If safe to remove, remove. If not, update documentation.
