### ISSUE TITLE
Replace `admin:admin` default credentials with configuration file password

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#3285]
This issue describes the tasks required to replace the basic `admin:admin` default credentials with an alternative method which takes a provided password from the openseach.yml file to be used as the default password. This issue results from:

Feedback from @peternied and @cwperks on a spike I created. 

While I think OTP could be a useful feature down the road, specifically for addressing requests to be able to run as a superadmin while SSL is disabled, for now, we can start with making the default password configurable via a configuration file value and a env. variable.

Craig said:

"
I like this approach and have seen it used in a number of places. Here's an example for keycloak where its passed in as an env variable in a docker-compose file:

```
version: '3'
services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres

volumes:
  postgres_data:
      driver: local

networks:
  opensearch-net:

```

I'd like to try to keep the simplicity of starting a demo cluster with [docker-compose](https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/#sample-docker-composeyml), where someone trying to start a cluster with the sample docker-compose.yml file can do docker-compose up and the cluster is brought up.

With the env variable approach, there would be one additional step to bring up a node or starting the cluster with docker. It would be to supply OPENSEARCH_ADMIN_PASSWORD or the node could not be brought up. A sample docker-compose.yml file for a single node could look like:

```
version: '3'
services:
  opensearch-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1,opensearch-node2 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - "OPENSEARCH_ADMIN_PASSWORD=w3akP@ssw0rd2023!"
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
```

In addition to admin:admin being widely known there are a few other widely known secrets too:

    The admin certificate and key should also be treated as a default password (they are) and anyone connecting with them can do anything
    `kibanaserver:kibanaserver`
  "

And I agree. 

The tasks required for these are listed on the document linked above, so I won't duplicate them here. Support for the configuration file will be prioritized first but both should ultimately be supported.

The tasks required to complete this include:

- [x] Add new blank configuation file to config (1 hour) 
- [ ] Update documentation (1 hour)
- [x] Add code to parse the provided doc on launch (1 hours) 
- [x] Reconcile configuration issues for multi-node clusters (1 day) 
- [x] Make sure nodes sync admin credentials in config to match the provided config (1 day)
