### ISSUE TITLE
`disabled_transport_categories` setting on an audit logging config may be unnecessary after transport client removal 

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#3380]
Since OpenSearch 2.0, support for the transport client has been removed. The transport client was removed from the security plugin in this PR: https://github.com/opensearch-project/security/pull/1701

My understanding of [disabled_transport_categories](https://github.com/opensearch-project/security/blob/main/config/audit.yml#L22C5-L24) is that it is used to enable an audit logging to log events from originating from the transport client.

Below is an example of a audit logging config of the security plugin's audit.yml file from the demo configuration:

```
config:
  # enable/disable audit logging
  enabled: true

  audit:
    # Enable/disable REST API auditing
    enable_rest: true

    # Categories to exclude from REST API auditing
    disabled_rest_categories:
      - AUTHENTICATED
      - GRANTED_PRIVILEGES

    # Enable/disable Transport API auditing
    enable_transport: true

    # Categories to exclude from Transport API auditing
    disabled_transport_categories:
      - AUTHENTICATED
      - GRANTED_PRIVILEGES
```

The `disabled_transport_categories` setting may not be needed here after the TransportClient's removal.

First: Determine if it is safe to remove values from settings.
Second: If safe to remove, remove. If not, update documentation.
