### ISSUE TITLE
[Question] Should the demo install script be translated to Java tool?

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#3632]
~_@DarshitChanpura to add more details related to design_~
Done. Please refer to [comment](https://github.com/opensearch-project/security/issues/3632#issuecomment-1789197089) to understand the approach. 

Exit Criteria:

- [x] A decision is made whether script should be translated to Java tool by identifying blast radius

**Comment by cwperks** [comment]
IMO if the goal is to rid the demo configuration of static secrets, then I think a solution should address all static secrets at once (certs, internal user passwords, opensearch_dashboards.yml). 

A potential solution could be an interactive CLI similar to `./install_demo_configuration.sh`, but takes more steps to setup all required secrets. Minimally, the secrets that would need to be generated are all of the certificates (root-ca, es-node cert and key, admin cert and key), the admin password and the kibanaserver password. What are all of the other reserved [internal users](https://github.com/opensearch-project/security/blob/main/config/internal_users.yml) used for?

i.e. I'm thinking something along the lines of:

```
./plugin/opensearch-security/tools/setup_security.sh

admin password:
>

Generate self-signed certs? (Y/n): 
>

Admin DN:
>

kibanaserver password:
>
```

For docker, can it be required to run this script ahead of time and then mount files/set environment variables accordingly?

i.e.

```
version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch-node1
    volumes:
      - ./path/to/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
      - <other security yml files>
      - ./path/to/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./path/to/esnode.pem:/usr/share/opensearch/config/esnode.pem
      - ./path/to/esnode-key.pem:/usr/share/opensearch/config/esnode-key.pem
      - ./path/to/admin.pem:/usr/share/opensearch/config/admin.pem
      - ./path/to/admin-key.pem:/usr/share/opensearch/config/admin-key.pem
```
