### ISSUE TITLE
Necessary permissions for kibana to work ?

### ISSUE THREAD

**Issue by Thoro** [opensearch-project/security#379]
I ran into an issue here: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/166

Basically the user does not get permissions to edit / update the corresponding indices which are referenced by the tenant, by having

```
  tenant_permissions:
  - tenant_patterns:
    - "Limited"
    allowed_actions:
    - "kibana_all_read"
    - "kibana_all_write"
```

I was under the impression, that for this tenant the user will have read and write permissions for all tenant indices, when using index_permissions it seems this is not the case.

Is this expected behaviour?
Shouldn't a tenant_permission add implicit permissions similar to the kibana_user role?
Do I have to add the kibana_user role to everyone? (which would negate the tenant permissions again)

**Comment by Anthony7774** [comment]
@Thoro Just tested with opensearch 1.2.0 and I'm not able to reproduce the issue.

My role looks like this:

```
test_role:
  index_permissions:
  - index_patterns:
    - "opensearch_dashboards_sample_data_flights"
    fls: []
    masked_fields: []
    allowed_actions:
    - "indices_all"
  tenant_permissions: 
    - tenant_patterns:
      - 'test'
      allowed_actions:
        - 'kibana_all_write'
```

The index permission is used to view the index and create index template in "test" tenant. 

If you are still having this issue, can you provide steps to reproduce?
