### ISSUE TITLE
how to have multiple AD groups configured for auth-z

### ISSUE THREAD

**Issue by anukalady** [opensearch-project/security#384]
Hi OD community,

we have been configuring LDAP/AD authentication.

The **rolebase** is configured to add one AD group. Is there a way that we can have multiple AD groups configured and role is formed from the CN of the ad group?
Wit this approach we can separate admins, application users and frontend users with different AD groups.

Thanks
AK

**Comment by Anthony7774** [comment]
@anukalady 
This is indeed possible (tested with opensearch) by using the below config in authz section:

```
authz:   
  ldap:
    http_enabled: true
    transport_enabled: false
    authorization_backend:
      type: ldap
      config:
        enable_ssl: false
        enable_start_tls: false
        enable_ssl_client_auth: false
        verify_hostnames: false
        hosts:
          - 192.168.0.13
        bind_dn: 'cn=test-user,cn=users,dc=local,dc=local'
        password: ******
        userbase: 'cn=Users,dc=local,dc=local'
        usersearch: '(uid={0})'
        username_attribute: uid
        roles:
          primary-rolebase:
            base: 'ou=groups,dc=example,dc=com'
            search: '(uniqueMember={0})'
          secondary-rolebase:
            base: 'ou=GroupsNew,dc=local,dc=local'
            search: '(member={0})'
        userroleattribute: null
        userrolename: none
        rolename: cn
        resolve_nested_roles: true
```

Similar can be done for userbase/search
