### ISSUE TITLE
Resource permission management

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3890]

**Comment by cwperks** [comment]
@peternied Does the new permission section also need `allowed_actions` as well? i.e. User can search on views x, y and z? How would permission to create or delete views be handled? Will it be similar to how indices work today?

Does the `resource_ids` section accept wildcards or are those exact matches only?

**Comment by peternied** [comment]
@cwperks Thanks for the questions

> Does the new permission section also need allowed_actions as well?

I avoided adding `allowed_actions` as I had a hard time thinking of how to express these in a way that wouldn't become hard to read given either 1) a lot of different resources and 2) a lot of different actions that can be applied to those resources.  Ways that I was considering would require sorting/ordering of values so its easy to find items.  I figure a simpler approach could be expanded after time.

To your question specifically, for the permission calculation in the prototype I used is Rest/Transport action name allowed && is the resource id in the list of allowed items.  While this prevents granular this or that kinds of permissions in a single role, maybe multiple roles is the better solution than making a single role support the more complex matrix with the traditional cluster permissions.

### Example roles
```yml
read_only_view:
  cluster_permissions:
    - cluster:views:list
    - cluster:views:get
    - cluster:views:search
  resource_permissions:
    - resource_type: view
      resource_ids: ["songs", "albums"]
```
```yaml
read_write_views:
  cluster_permissions:
    - cluster:views:search
    - cluster:views:list
    - cluster:views:create
    - cluster:views:get
    - cluster:views:delete
    - cluster:views:update
  resource_permissions:
    - resource_type: view
      resource_ids: ["*"]
```
_Note: if you can create views its strange not to have wildcard resource access_
