### ISSUE TITLE
[BUG] The 2.12.0 initial deployment prevents the usage of the custom internal_users.yml file.

### ISSUE THREAD

**Issue by tomte76** [opensearch-project/security#4098]
Upgrade to 2.12.0, in my case using helm on kubernetes, failed with an error message related to setting OPENSEARCH_INITIAL_ADMIN_PASSWORD. The error message is:

`Exception updating the admin password : /usr/share/opensearch/config/opensearch-security/internal_users.yml: Device or resource busy`

As I understand the user pablo in the forum, you can use any deployment with defined internal users in the values.yml or in my case having an existing kubernetes secret used in the helm deployment and new parameter set in values.yaml:

extraEnvs: 
  - name: "OPENSEARCH_INITIAL_ADMIN_PASSWORD"
    value: "some_strong_password_here"

Please find more information in the [forum discussion](https://forum.opensearch.org/t/problem-with-the-default-admin-passwort/18030).

**What is the expected behavior?**

Upgrade succeeds and the existing security configuration is preserved.

**What is your host/environment?**
 - OS:  Debian 12 amd64
-  Kubernetes v1.29 
 - Version: OpenSearch 2.11.1 to 2.12.0 upgrade with helm charts 2.17.0 to 2.18.0

**Comment by pawelw1** [comment]
This issue has been discussed and tested in the OpenSearch forum.

https://forum.opensearch.org/t/problem-with-the-default-admin-passwort/18030/11

The reported error appears when both internal_users and extraEnvs OPENSEARCH_INITIAL_ADMIN_PASSWORD are defined in values.yml during the deployment. 
The working scenario is when only extranEnvs OPENSEARCH_INITIAL_ADMIN_PASSWORD is configured. This issue prevents from using custom internal_users.yml during the deployment.

**Comment by DarshitChanpura** [comment]
@prudhvigodithi Can you please help here since I believe you are familiar with this issue?

**Comment by DarshitChanpura** [comment]
While we wait for inputs from @prudhvigodithi, @tomte76 Here is a comment from another user who faced similar issue: https://github.com/opensearch-project/helm-charts/issues/519#issuecomment-1965673393

If your use-case is to setup demo certificates via demo config, you can instead generate custom certs and mount them. Here is a possible solution: https://github.com/opensearch-project/helm-charts/issues/519#issuecomment-1971014286

**Comment by prudhvigodithi** [comment]
To make it work with helm charts with this new security change, the way is to create the `internal_users.yml` as `configmap` and use `initContainers` to avoid the error `Device or resource busy`.
(https://github.com/opensearch-project/security/issues/3891#issuecomment-1958398284)

`kubectl create configmap internal-users --from-file=internal_users.yml=internal_users.yml`

```
extraVolumes:
  - name: internal-users-emptydir
    emptyDir: {}
  - name: internal-users
    configMap:
      name: internal-users
      items:
      - key: internal_users.yml
        path: internal_users.yml

extraVolumeMounts:
    - name: internal-users-emptydir
      mountPath: /usr/share/opensearch/config/opensearch-security/
      subPath: internal_users.yml
    - name: internal-users
      mountPath: /tmp/internal_users.yml
      subPath: internal_users.yml
   
extraInitContainers:
  - name: internal-users-init-container
    image: busybox
    command: ['sh', '-c', 'cp /tmp/internalusers/internal_users.yml /tmp/internal_users.yml']
    volumeMounts:
    - mountPath: /tmp/internal_users.yml
      subPath: internal_users.yml
      name: internal-users-emptydir
    - name: internal-users
      mountPath: /tmp/internalusers/internal_users.yml
      subPath: internal_users.yml
```

Set the `securityConfig.config.dataComplete` to `false`.

Adding @peterzhuamazon @bbarani
