### ISSUE TITLE
[BUG] `system:admin/system_index` search results do not include any documents

### ISSUE THREAD

**Issue by llilyy** [opensearch-project/security#4188]
**What is the bug?**

I've set the permission `system:admin/system_index` on `internal_index_manager` role for reading the custom system index.
The user (binding `internal_index_manager` role) can write documents and the `_search` API works, but it cannot search documents (no hit items).
Only super admin can search documents.
Is this by design? If it was intentional, I wonder the reason.

**How can one reproduce the bug?**

### Test based reproduction

In SystemIndexPermissionEnabledTests.SystemIndexPermissionEnabledTests should expect 1 document to be returned, edit the call to validateSearchResponse second parameter from 0 -> 1.

https://github.com/opensearch-project/security/blob/4e8297aa4253c675526a803651a9214fe4e02962/src/test/java/org/opensearch/security/system_indices/SystemIndexPermissionEnabledTests.java#L72-L84

---
#### config

```yml
plugins.security.system_indices.enabled: true
plugins.security.system_indices.permission.enabled: true
plugins.security.system_indices.indices: [".my-system-index"]
```

#### role

```yml
internal_index_manager:
  reserved: true
  hidden: true
  description: ""
  index_permissions:
    - index_patterns:
        - ".my-system-index"
      allowed_actions:
        - "*"
        - "system:admin/system_index"
```

#### user

```yml
manager:
  hash: "{hash}"
  reserved: true
  opendistro_security_roles:
    - "internal_index_manager"
  description: ""
```

#### CAT indices

```
health status index                  uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   .my-system-index U-HWdSsKTi2oqcrVNgPqfQ   1   1          1            0     10.4kb         10.4kb
```

#### SEARCH result

```
GET https://{ip}:{port}/.my-system-index/_search
Authorization: Basic {user_token}
```
```json
{
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 0,
      "relation": "eq"
    },
    "max_score": null,
    "hits": [] // cannot read documents. no hit item.
  }
}
```

**What is the expected behavior?**

#### expected SEARCH result

```json
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1.0,
    "hits": [
      {
        "_index": ".my-system-index",
        "_id": "1",
        "_score": 1.0,
        "_source": {
          "field": "value"
         }
       }
     ] // want to get hit items of the custom system index
  }
}
```

**What is your host/environment?**
```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
```
 - Plugins: 2.11.1

**Do you have any screenshots?**

**Do you have any additional context?**
