### ISSUE TITLE
[FEATURE] how about accessing `Monitor API` with out additional authentication

### ISSUE THREAD

**Issue by 10000-ki** [opensearch-project/security#4215]
**Is your feature request related to a problem?**

The following APIs may be used in the k8s probe to determine whether the container is healthy 
ex) readiness, liveness probe
 - /_cluster/health
 - /_cat/health

For convenience, I would like to avoid any authentication in this part.

Or we have to put authentication information like this, but it's very disturbing to expose authentication information like this.

```yml
livenessProbe:
  httpGet:
    path: /_cluster/health
    port: 9200
    httpHeaders:
      - name: Authorization
        value: Basic aGE6aGE=
```

**What solution would you like?**

- [SecurityFilter.java](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/filter/SecurityFilter.java#L211C13-L211C126)
- [SecurityRestFilter.java](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/filter/SecurityRestFilter.java)

We can ignore the authentication check for monitor-related APIs in the security filter

```java
final boolean passThroughRequest = action.startsWith("indices:admin/seq_no") || action.equals(WhoAmIAction.NAME) || action.startsWith("cluster:monitor");
```

...

**What alternatives have you considered?**

no

**Do you have any additional context?**

no
