### ISSUE TITLE
[BUG] Even though it is not a system index, document cannot be searched due to a bug

### ISSUE THREAD

**Issue by 10000-ki** [opensearch-project/security#4429]
**What is the bug?**

```yml
plugins.security.system_indices.enabled: true
plugins.security.system_indices.permission.enabled: true
```

After enabling the system index-related settings

Documents in normal indexes, which are not system indexes, cannot be queried. 
The reason is that when the `plugins.security.system_indices.permission.enabled` condition is enabled
the `SecurityIndexSearcherWrapper` [checks for the `system:admin/system_index` permission for all indexes](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/configuration/SecurityIndexSearcherWrapper.java#L155), regardless of whether they are system indexes or not.

now we resolve this issue, it is necessary to grant the `system:admin/system_index` permission to regular users as well. This can be done as follows:

```yml
normal_user:
  reserved: false
  hidden: false
  cluster_permissions:
    - "*"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "*"
        - "system:admin/system_index"
```

However, this does not seem to be an good solution.

**How can one reproduce the bug?**

### 1. Starting OpenSearch with system index settings enabled.

```yml
plugins.security.system_indices.enabled: true
plugins.security.system_indices.permission.enabled: true
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opensearch-notifications-*", ".opensearch-notebooks", ".opensearch-observability", ".ql-datasources", ".opendistro-asynchronous-search-response*", ".replication-metadata-store", ".opensearch-knn-models"]
```

### 2. create index & document with normal user account

- account : `user:user`

```yml
    user:
      reserved: false
      hidden: false
      cluster_permissions:
        - "*"
      index_permissions:
        - index_patterns:
            - "*"
          allowed_actions:
            - "*"
 ```

```json
PUT http://localhost:9200/test-index/_doc/1

{
    "foo": "bar"
}


{
    "_index": "test-index",
    "_id": "1",
    "_version": 1,
    "result": "created",
    "_shards": {
        "total": 2,
        "successful": 1,
        "failed": 0
    },
    "_seq_no": 0,
    "_primary_term": 1
}

```

=> `Document was created well.`

### 3. Searching documents with a user account that does not have system index permissions. 

- account : `user:user`

```yml
    user:
      reserved: false
      hidden: false
      cluster_permissions:
        - "*"
      index_permissions:
        - index_patterns:
            - "*"
          allowed_actions:
            - "*"
 ```

```
GET http://localhost:9200/test-index/_search

{
    "took": 11,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 0,
            "relation": "eq"
        },
        "max_score": null,
        "hits": []
    }
}
```

=> `Documents cannot be searched.`

**What is the expected behavior?**
System index permission checks should be limited to system indexes only. 
Indexes that are not system indexes should be queryable without permission checks.

**What is your host/environment?**
 - OS: Linux, MacOS
 - Version
 - Plugins
    - Security Plugin

**Do you have any screenshots?**

![스크린샷 2024-06-11 오전 1 04 25](https://github.com/opensearch-project/security/assets/76486121/8fe0cdea-b64a-4f06-adbd-5708568c8b53)

![스크린샷 2024-06-11 오전 1 04 38](https://github.com/opensearch-project/security/assets/76486121/4d16cc58-3f37-4834-aa2b-1a51f0ee441f)

![스크린샷 2024-06-11 오전 1 05 20](https://github.com/opensearch-project/security/assets/76486121/00066f65-e011-4f39-867f-adeb23409104)

**Do you have any additional context?**
Add any other context about the problem.
