### ISSUE TITLE
cluster remote search

### ISSUE THREAD

**Issue by hihouhou** [opensearch-project/security#50]
Hello,
remote cluster is up and available but I can't see indices.
About doc https://opendistro.github.io/for-elasticsearch-docs/docs/security/cross-cluster-search/ 
where have to put this lines ?
Is it possible to give me a full example ?
Regards

**Comment by aetter** [comment]
Hi @hihouhou, those lines are from `roles.yml`, but as far as I know, you should be able to create a role in Kibana (using an admin user) that has those same permissions. Can you try something like the following?

![example](https://user-images.githubusercontent.com/9122297/58135076-e155db80-7bdd-11e9-8a3c-cabfef688feb.png)

**Comment by hihouhou** [comment]
I tried this but nothing :-( 
```
proxy_elas ~ 0 # curl -XGET -H 'Content-Type: application/json' https://127.0.0.1:9200/_remote/info?pretty -u admin:admin
{
  "toto" : {
    "seeds" : [
      "toto.service.consul:9300"
    ],
    "http_addresses" : [
      "XX.XX.XX.XX:9200",
      "XX.XX.XX.XX:9200",
      "XX.XX.XX.XX:9200"
    ],
    "connected" : true,
    "num_nodes_connected" : 3,
    "max_connections_per_cluster" : 3,
    "initial_connect_timeout" : "30s",
    "skip_unavailable" : false
  }
}


remote_elas ~ 130 # curl -sX GET "https://127.0.0.1:9200/_cluster/health" -u admin:admin | jq .
{
  "cluster_name": "remote",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 3,
  "number_of_data_nodes": 3,
  "active_primary_shards": 76,
  "active_shards": 153,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}

remote_elas ~ 0 # curl -X GET -s "https://127.0.0.1:9200/_opendistro/_security/api/roles/humanresources" -u admin:admin | jq .
{
  "humanresources": {
    "cluster": [
      "CLUSTER_COMPOSITE_OPS_RO"
    ],
    "indices": {
      "hihouhou": {
        "*": [
          "READ",
          "indices:admin/shards/search_shards ¸ needed for CCS"
        ]
      }
    }
  }
}



remote_elas ~ 130 # curl -X GET "https://127.0.0.1:9200/_cat/indices" -u admin:admin
...
green open hihouhou-2019.05.19          05PjMQMMS0uV4gSkmHBOHA 5 1     0 0   2.5kb    1.2kb
green open hihouhou-2019.05.18          tH6zCimOSXeDFW05VNTv2w 5 1     0 0   2.5kb    1.2kb
...


proxy_elas ~ 0 # curl -ks 'https://127.0.0.1:9200/_cluster/health?pretty=true' -u admin:admin
{
  "cluster_name" : "proxy",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 3,
  "number_of_data_nodes" : 3,
  "active_primary_shards" : 138,
  "active_shards" : 277,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}



```

**Comment by prashar** [comment]
Hello, 

You can try the following - start 2 elasticsearch nodes, one on 9250 and 9000 .. You may use my docker compose file:

```
version: '3'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:0.9.0
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-net
  kibana-1:
    image: amazon/opendistro-for-elasticsearch-kibana:0.9.0
    container_name: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://odfe-node1:9200
      ELASTICSEARCH_HOSTS: https://odfe-node1:9200
    networks:
      - odfe-net

  odfe-node2:
    image: amazon/opendistro-for-elasticsearch:0.9.0
    container_name: odfe-node2
    environment:
      - cluster.name=odfe-cluster-2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data2:/usr/share/elasticsearch/data
    ports:
      - 9250:9200
      - 9700:9600 # required for Performance Analyzer
    networks:
      - odfe-net
  kibana-2:
    image: amazon/opendistro-for-elasticsearch-kibana:0.9.0
    container_name: odfe-kibana-2
    ports:
      - 5603:5601
    expose:
      - "5603"
    environment:
      ELASTICSEARCH_URL: https://odfe-node2:9200
      ELASTICSEARCH_HOSTS: https://odfe-node2:9200
    networks:
      - odfe-net

volumes:
  odfe-data1:
  odfe-data2:

networks:
  odfe-net:
```

After running docker-compose -up, you need to find the IP address of each container, do the following:

```
➜ ~ docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
cbd47a0625e0 amazon/opendistro-for-elasticsearch-kibana:0.9.0 "/usr/local/bin/kiba…" About a minute ago Up 57 seconds 5603/tcp, 0.0.0.0:5603→5601/tcp odfe-kibana-2
381bef7218fb amazon/opendistro-for-elasticsearch:0.9.0 "/usr/local/bin/dock…" About a minute ago Up 57 seconds 0.0.0.0:9200→9200/tcp, 0.0.0.0:9600→9600/tcp, 9300/tcp odfe-node1
c5779c179ca7 amazon/opendistro-for-elasticsearch-kibana:0.9.0 "/usr/local/bin/kiba…" About a minute ago Up 58 seconds 0.0.0.0:5601→5601/tcp odfe-kibana
da6f5e51edfa amazon/opendistro-for-elasticsearch:0.9.0 "/usr/local/bin/dock…" About a minute ago Up 58 seconds 9300/tcp, 0.0.0.0:9250→9200/tcp, 0.0.0.0:9700→9600/tcp odfe-node2
```

```
➜  ~ docker inspect -f 'range .NetworkSettings.Networks.IPAddressend' 381bef7218fb
192.168.48.4
➜  ~ docker inspect -f 'range .NetworkSettings.Networks.IPAddressend' da6f5e51edfa
192.168.48.2
```

Notice my 9200 ES container's ip address is 192.168.48.4, and the 9250 is 192.168.48.2

In this example, we will try to search the 9200 container through 9250, so add the following to 9250 ES container. 

```
➜  ~ curl -k -XPUT -H 'Content-Type: application/json' https://admin:admin@localhost:9250/_cluster/settings -d '
{
    "persistent": {
        "search.remote": {
            "odfe-cluster": {
                "seeds": ["192.168.48.4:9300"]
            }
        }
    }
}'
{"acknowledged":true,"persistent":{"cluster":{"remote":{"odfe-cluster":{"seeds":["192.168.48.4:9300"]}}}},"transient":{}}%
```

After this step, you should be able to 

```
➜ ~ curl -XGET -k https://admin:admin@localhost:9250/_remote/info\?pretty (https://admin:admin@localhost:9250/_remote/info/?pretty)
{
"odfe-cluster" : {
"seeds" : [
"192.168.48.4:9300"
],
"http_addresses" : [
"192.168.48.4:9200"
],
"connected" : true,
"num_nodes_connected" : 1,
"max_connections_per_cluster" : 3,
"initial_connect_timeout" : "30s",
"skip_unavailable" : false
}
}

```
Let's now create a searchable index on 9200, and add some data(optional)

```
➜ ~ curl -XPUT -k https://admin:admin@localhost:9200/books
{"acknowledged":true,"shards_acknowledged":true,"index":"books"}%
```

NOW, let's do a cross cluster search using admin credentials, it will be able to make the call across clusters - the reason this works is because I am passing in admin credentials. 

```
➜ ~ curl -XGET -k https://admin:admin@localhost:9250/odfe-cluster:books/_search
{"took":207,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"_clusters":{"total":1,"successful":1,"skipped":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"odfe-cluster:books","_type":"fiction","_id":"1","_score":1.0,"_source":{"name": ...
```

What if you didn't want to use admin credentials - in that case you need do the following: 

First, let's create a user, call it booksuser on 9250 and 9200

```
curl -XPUT -k https://admin:admin@localhost:9250/_opendistro/_security/api/internalusers/booksuser  -H 'Content-Type: application/json' -d '{"password":"password"}'
{"status":"CREATED","message":"'booksuser' created."}%

curl -XPUT -k https://admin:admin@localhost:9200/_opendistro/_security/api/internalusers/booksuser  -H 'Content-Type: application/json' -d '{"password":"password"}'
{"status":"CREATED","message":"'booksuser' created."}%
```

Now, let's run the same command we used to cross cluster search using this new booksuser. 

```
curl -XGET -k https://booksuser:password@localhost:9250/odfe-cluster:books/_search
{"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [indices:admin/shards/search_shards, indices:data/read/search] and User [name=booksuser, roles=[], requestedTenant=null]"}],"type":"security_exception","reason":"no permissions for [indices:admin/shards/search_shards, indices:data/read/search] and User [name=booksuser, roles=[], requestedTenant=null]"},"status":403}%
```

You can see what error message is telling you .. you need a role providing those index permissions to the booksuser, you may do so like this - NOTE - you need to create both role and the role mapping. 

```
➜  ~ curl -XPUT -k https://admin:admin@localhost:9250/_opendistro/_security/api/roles/booksrole -H 'Content-Type: application/json' -d '{"indices" : {"books" : {"" : [ "indices:admin/shards/search_shards","indices:data/read/search"]}}}' -i -v   Trying ::1...

* TCP_NODELAY set
* Connected to localhost (::1) port 9250 (#0)
* WARNING: disabling hostname validation also disables SNI.
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: node-0.example.com (http://node-0.example.com/)
* Server auth using Basic with user 'admin'

> PUT /_opendistro/_security/api/roles/booksrole HTTP/1.1
> Host: localhost:9250
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.54.0
> Accept: /
> Content-Type: application/json
> Content-Length: 100
>

* upload completely sent off: 100 out of 100 bytes

< HTTP/1.1 201 Created
HTTP/1.1 201 Created

```

```
*➜  ~ curl -XPUT -k https://admin:admin@localhost:9250/_opendistro/_security/api/rolesmapping/booksrole -H 'Content-Type: application/json' -d '{"users" : ["booksuser"]}' -i -v*

*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9250 (#0)
* WARNING: disabling hostname validation also disables SNI.
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: node-0.example.com (http://node-0.example.com/)
* Server auth using Basic with user 'admin'

> PUT /_opendistro/_security/api/rolesmapping/booksrole HTTP/1.1
> Host: localhost:9250
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.54.0
> Accept: /
> Content-Type: application/json
> Content-Length: 25
>

* upload completely sent off: 25 out of 25 bytes

< HTTP/1.1 201 Created
HTTP/1.1 201 Created
```

Now, you will be able to run the command and do cross cluster search ->

```
➜  ~ curl -XGET -k https://booksuser:password@localhost:9250/odfe-cluster:books/_search
{"took":63,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"_clusters":{"total":1,"successful":1,"skipped":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"odfe-cluster:books","_type":"fiction","_id":"1","_score":1.0,"_source":{"name": "H....
```
