### ISSUE TITLE
Tiny documentation discrepancy

### ISSUE THREAD

**Issue by antonvigo** [opensearch-project/security#5211]
**NON URGENT**

[Here](https://opensearch.org/docs/latest/security/configuration/index/#reconfigure-configyml-to-use-your-authentication-backend) in docs there is a statement: "For example, to use **LDAP** as your authentication backend, add the following settings:" with internal auth configuration example below:
```
    authc:
      basic_internal_auth:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal
```

**Expected behavior:**
Replace LDAP with internal.
