### ISSUE TITLE
[BUG] Issue computing diffs in compliance audit log when writing to security index

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security#5280]
**What is the bug?**

Security index write diffs always include full document due to silent `getForUpdate` failure

When compliance audit logging is enabled for the security index, any write operation appears to be creating a full-document “diff” instead of just the delta. This happens because `ComplianceIndexingOperationListenerImpl`'s call to retrieve the previous document state via `getForUpdate` fails silently and returns an empty document. As a result, every update looks like a brand‑new document rather than a partial change.

**How can one reproduce the bug?**

1. Enable compliance audit diffs in opensearch.yml (see sample below).

2. Perform any change that results in an update to .opendistro_security index. i.e. add user attributes

3. Inspect the audit log

4. Observe that the audit log’s diff payload contains the entire document (ctype) rather than only the changed fields.

<details> <summary><strong>audit.yml</strong></summary>

```
_meta:
  type: "audit"
  config_version: 2

config:
  enabled: true
  audit:
    enable_rest: true
    disabled_rest_categories: [AUTHENTICATED, GRANTED_PRIVILEGES]
    enable_transport: true
    disabled_transport_categories: [AUTHENTICATED, GRANTED_PRIVILEGES]
    ignore_users: [kibanaserver]
    resolve_bulk_requests: false
    log_request_body: false
    resolve_indices: true
    exclude_sensitive_headers: true

  compliance:
    enabled: true
    internal_config: true
    external_config: false
    read_metadata_only: true
    read_ignore_users: [kibanaserver]
    write_metadata_only: false
    write_log_diffs: true
    write_watched_indices: ["movies"]   # add "security" or wildcard to include security index
    write_ignore_users: [kibanaserver]
```

</details>

Ensure that:

- `config.compliance.enabled`: true

- `config.compliance.write_log_diffs`: true

- `config.compliance.write_metadata_only`: false
