### ISSUE TITLE
[RFC] New format for role configuration

### ISSUE THREAD

**Issue by nibix** [opensearch-project/security#5317]
# Background

OpenSearch security uses the roles.yml configuration to associate user roles with permissions.

For simple cases, this works quite well. However, for more advanced cases it gets apparent that some concepts have disadvantages from a security point of view or from a UX point of view.

This RFC elaborates briefly on the issues and gives then a proposal for a new format.

**Important:** This is just a first shot for a discussion. I am already aware of a couple of potential weaknesses. Please feel invited to say: "That's overengineered" :)

# Issues with current roles.yml

## No concept for extensibility

There are a couple of cases where there is a desire to extend the role configuration by introducing new dimensions for privileges. The most recent one is the introduction of privileges for settings. See #5219 for details. In the past, there were also conversations about extending the roles configuration by privileges for resources defined by plugins.

Adding new properties to the roles.yml configuration leads to the question how backwards compatibility is handled. Usually, users on old configurations expect to have full privileges. 

The straight forward idea is to keep the old behavior on absence of the new configuration properties. The presence of new configuration properties leads then to reduced privileges.

In consequence that means that users get *by default* full privileges on a dimension. An admin has then the option to reduce privileges using configuration. This is in contradiction to the *principle of least privilege*, which IMHO should be a basic architectural property for security software.

## Definition of DLS rules

The way DLS rules are configured is also not really in line with the principle of least privilege. The absense of a DLS rule (i.e. the default state) means full privileges:

```
role_a:
  index_permissions:
    - index_patterns:
      - index_a
      allowed_actions:
        - read
```

It is necessary to explicitly configure a DLS rule to restrict privileges.

```
role_a:
  index_permissions:
    - index_patterns:
      - index_a
      allowed_actions:
        - read
      dls: '{ "bool": { "must_not": { "match": { "department": "Management" }}}}'
```

## Scope of DLS rules

The way DLS rules are interpreted can be surprising. There is the setting `plugins.security.dfm_empty_overrides_all` which allows to control the behavior of the settings. (See https://docs.opensearch.org/docs/latest/security/access-control/document-level-security/#when-to-enable-pluginssecuritydfm_empty_overrides_all ) It allows two states: true/false. Both states have issues. 

In state `false`, there is no way to lift DLS restrictions applied by one role by another role. As soon as a user has a role with DLS restrictions, the only way to remove this restriction would be removing this role. This is in contraction to the assumption that adding more roles to a user expands the granted privileges. In this cases, adding more roles to a user has the potential of reducing granted privileges.

In state `true`, this is more logical: The presence of an unrestricted role gives full access, even if there are also restricted roles.

However, there's still another suprising behavior. Consider the following configuration:

```
role_a:
  index_permissions:
    - index_patterns:
      - index_a
      allowed_actions:
        - read
      dls: '{ "bool": { "must_not": { "match": { "department": "Management" }}}}'
```

```
role_b:
  index_permissions:
    - index_patterns:
      - index_a
      allowed_actions:
        - monitor
```

This is a comon scenario: A user shall be able to read a restricted set of documents from an index. Meanwhile the user still shall be able to use monitoring functionality on that index (that functionality does not give document access, so no DLS rule should be necessary).

However, assigning both roles to a user has the effect of lifting DLS restrictions for the specified index `index_a`. This is because `role_b` has no DLS rule and thus indicates full document access to the index.

Most users would expect that DLS rules specified in roles only apply to the action referenced in the same role (`monitor` in this case). However, this is not true. The DLS rules apply to all actions, regardless of the actions specified in the role.

Fundamentally, the root issue is here the fact that full access to documents is an implicit property of the role - indicated by the *absence* of the rule.  These unclear situations would not arise if document access would need to be explicitly specified.

## Interaction of FLS rules

FLS rules can be specified in two modes:

- Including rules: You need to explicitly list the fields that are allowed
- Excluding rules: You list fields that are not allowed. All other fields are allowed by default

If a user gets both a role with including rules assigned and also another role with exluding rules, the results are likely unexpected. 

Consider the following example:

```
role_including_field_a:
  index_permissions:
    - index_patterns:
      - index_a
      allowed_actions:
        - read
      fls: field_a
```

```
role_excluding_field_a:
  index_permissions:
    - index_patterns:
      - index_a
      allowed_actions:
        - read
      fls: ~field_a
```

If a user gets assigned both roles, they will lose access to field_a. This is because mixing inclusion and exclusion effectively leads to disregarding all including rules.

Note: This behavior is undocumented. The documentation should says that mixing inclusion and exclusion is not recommended: https://docs.opensearch.org/docs/latest/security/access-control/field-level-security/#interaction-with-multiple-roles

# Proposal

## Goals

Fundamental properties of a revised role configuration should be the following:

- Explicitness: Full access to documents, fields, settings, etc. should be always configured in an explicit way. 
- Priniciple of least privilege: The explicit configuration automatically helps to adhere to the principle of least privilege.
- Extensibility: Have a concept on how add new dimensions without disrupting backwards compatibility and principle of least privilege.
- No surprises: Make all configuration elements follow well-defined principles

## Example

```yaml
test_role:
  - grant:
      - cluster:admin/settings/*
    on:
      scope: cluster
      settings:
        - cluster.routing.*
  - grant:
      - index:read/*
    on:
      indices:
        - test_*
      documents:
        - *
      fields:
        - field_a
        - field_b:
            - hash: blake2b
        - field_c:
            - replace: /[0-9]{1,3}$/
              by: "XXX"
            - replace: /^[0-9]{1,3}/
              by: "***"
      settings:
        - *
      "*":
        - *
```

## Explicitness

The configuration requires the explicit configuration of all privileges. For example, all index related roles must specify `documents: *` and `fields: *` if they want to allow full access. This should make the behavior clear if roles with full access (which were previously without rules) and roles with restricted access are mixed.

Additionally, there's the option to leave out rules like `document: *`. This has then the property that document access in not modified by a particular role. This allows then the use case to give a user privileges for monitoring an index without having to think about document access.

There is the shortcut `"*": *` which acts as a fallback in case the other explicitly specified dimensions do not match a particular dimension. This gives explicit grant for all dimensions which were not specified otherwise. This should be only used for admin users which shall have high privileges. 

## Extensibility

To a certain extent, the `"*": *` construct allows extensibility - at least for admin users. If it is used for admin users,  it makes sure that admin users cannot lose privileges when new privilege dimensions are introduced. Still, it is an explicit signal that a user has elevated permissions.

Open question: Users without this construct are not covered by this extensibility construct. Is the extensibility concept still sufficient or do we also need a way to consider these users?

## Expressive names of config options

Using expressive names like `documents` and `fields` instead of `dls` and `fls` leads to configuration documents which are more easy to intuitively read and understand.

## Refined semantics

The new configuration format gives us the chance to refine semantics for example for FLS. 

# Comments

Please feel invited to share your thoughts. I am pretty convinced that also this proposal has a couple of weaknesses. Can we improve these?
