### ISSUE TITLE
[BUG] Audit log cut off

### ISSUE THREAD

**Issue by Jakob3xD** [opensearch-project/security#5363]
**What is the bug?**
I want to log the audit logs via log4j as JSON and parse the JSON. I have to do this because externa_opensearch is not an option https://github.com/opensearch-project/security/issues/2142.
The outer JSON which gets logged is valid JSON but the audit message itself gets cut off, when the requests_body is to large.

```

  "type": "audit",
  "timestamp": "2025-05-26T09:11:39,653Z",
  "level": "INFO",
  "component": "audit",
  "cluster.name": "staging-opensearch1",
  "node.name": "staging-opensearch1-n1.example.com",
  "message": "{\"audit_cluster_name\":\"staging-opensearch1\",\"audit_rest_request_params\":{\"index\":\"staging-ingress\"},\"audit_node_name\":\"staging-opensearch1-n1.example.com\",\"audit_request_initiating_user\":\"staging-storage\",\"audit_rest_request_method\":\"POST\",\"audit_category\":\"AUTHENTICATED\",\"audit_request_origin\":\"REST\",\"audit_request_body\":\"{\ __REDACTED__",
  "cluster.uuid": "xyz",
  "node.id": "xyz"
}
```
So the `message` fields gets cut off at some point and the JSON struct is not closed.

**How can one reproduce the bug?**
Steps to reproduce the behaviour:
log4j config:
```
################# Audit log #####################
appender.audit_rolling.type = RollingFile
appender.audit_rolling.name = audit_rolling
appender.audit_rolling.fileName = ${sys:opensearch.logs.base_path}${sys:file.separator}audit.json
appender.audit_rolling.filePattern = ${sys:opensearch.logs.base_path}${sys:file.separator}audit-%i.json.gz
appender.audit_rolling.layout.type = OPENSEARCHJsonLayout
appender.audit_rolling.layout.type_name = audit
appender.audit_rolling.policies.type = Policies
appender.audit_rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.audit_rolling.policies.size.size = 5GB
appender.audit_rolling.strategy.type = DefaultRolloverStrategy
appender.audit_rolling.strategy.max = 4

logger.audit_rolling.name = audit
logger.audit_rolling.level = debug
logger.audit_rolling.appenderRef.audit_rolling.ref = audit_rolling
logger.audit_rolling.additivity = false
```
audit config:
```
_meta:
  type: "audit"
  config_version: 2
config:
  compliance:
    enabled: true
    write_log_diffs: false
    read_watched_fields: {}
    read_ignore_users:
    - "kibanaserver"
    write_watched_indices: []
    write_ignore_users:
    - "kibanaserver"
    external_config: false
    internal_config: true
    write_metadata_only: false
    read_metadata_only: false
  enabled: true
  audit:
    ignore_users:
    - "kibanaserver"
    ignore_requests:
    - "indices:data/write/bulk"
    disabled_rest_categories: []
    disabled_transport_categories: []
    resolve_bulk_requests: false
    enable_rest: true
    enable_transport: true
    log_request_body: true
    resolve_indices: true
    exclude_sensitive_headers: true
```
Perform larger _bulk requests.
Watch the audit logs.

**What is the expected behaviour?**
I expect to see the full audit log including the `audit_request_body`.

If logging the full `audit_request_body` is an issue, then only the `audit_request_body` should get cut off and not the complete message, as it results in invalid JSON.

**What is your host/environment?**
 - OS: 24.04
 - Version 2.19.2
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.
