### ISSUE TITLE
config.yml settings for OpenID Connect not working with nested hierarchy for roles

### ISSUE THREAD

**Issue by NickDatLe** [opensearch-project/security#551]
Hello,

I can't seem to get roles working when the roles_key field is not a simple key-value pair. For example, this works:

```yaml
              authc:
                openid_auth_domain:
                  http_enabled: true
                  transport_enabled: true
                  order: 0
                  http_authenticator:
                    type: openid
                    challenge: false
                    config:
                      subject_key: preferred_username
                      roles_key: roles
                      openid_connect_url: https://my-keycloak-server.com:8443/auth/realms/demo/.well-known/openid-configuration
                  authentication_backend:
                    type: noop
```

When the token looks like this, it works:

```json
      "roles": [
        "admin"
      ]
```

However, when I try to restructure the roles_key to this:

```yaml
              authc:
                openid_auth_domain:
                  http_enabled: true
                  transport_enabled: true
                  order: 0
                  http_authenticator:
                    type: openid
                    challenge: false
                    config:
                      subject_key: preferred_username
                      roles_key: resource_access.my-client-id.roles
                      openid_connect_url: https://my-keycloak-server.com:8443/auth/realms/demo/.well-known/openid-configuration
                  authentication_backend:
                    type: noop
```

and restructure my JWT to look like this:

```json
"resource_access": {
    "my-client-id": {
      "roles": [
        "admin"
      ]
    }
  }
```

I think it's the way I defined the "roles_key" field. Any help is appreciated.
