### ISSUE TITLE
Is there is a way to pass tenant-name, client_id, client_secret dynamically ?

### ISSUE THREAD

**Issue by devansvd** [opensearch-project/security#59]
**Question (1)** - Is there is a way to pass tenant-name, client_id, client_secret dynamically ? since it is hardcoded in the `kibana.yml` need to run multiple instance of kibana because of this.

kibana.yml:

 ```
    opendistro_security.auth.type: "openid"
    opendistro_security.openid.connect_url: https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration
    opendistro_security.openid.client_id: "{application_id}"
    opendistro_security.openid.client_secret: "{secret}"
    opendistro_security.openid.base_redirect_url: "https://kibana_url"
    elasticsearch.requestHeadersWhitelist: ["Authorization", "security_tenant"]
```
**Question (2)** - Also, The authentication token has the which tenant. Is it possible to pick the tenant name from token and check it in `openid_connect_url` ? similar to `roles_key: "roles"`

config.yml

 ```
opendistro_security:
        dynamic:
          http:
            anonymous_auth_enabled: false
            xff:
              enabled: true
              internalProxies: '.*' # trust all internal proxies, regex pattern
              remoteIpHeader:  'x-forwarded-for'
              proxiesHeader:   'x-forwarded-by'
              trustedProxies: '.*' # trust all external proxies, regex pattern
          authc:
            openid_auth_domain:
              http_enabled: true
              transport_enabled: true
              order: 0
              http_authenticator:
                type: openid
                challenge: false
                config:
                  openid_connect_url: https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration
                  roles_key: "roles"
              authentication_backend:
                type: noop
```
