### ISSUE TITLE
Issue with ldap users and Index Patters filters

### ISSUE THREAD

**Issue by e11it** [opensearch-project/security#74]
Hi!

We have an issue with ldap users and Index Patters filters in Security Roles.

Ldap user name contain dots. Example:

```
GET _opendistro/_security/authinfo
{
  "user" : "User [name=Ilya.Makarov, roles=[...], requestedTenant=]",
  "user_name" : "Ilya.Makarov",
```

User index for kibana looks like(without dot between name and surname):

```
.kibana_-434785236_ilyamakarov
```

We have created Security Role `kibana_ldap_user`:

```
{
  "index_permissions": [
    {
      "index_patterns": [
        ".kibana_*_${user_name}*",
```

But user doesn't have access to his index.

If replace index patterns to `.kibana_*_ilyamakarov*` - permmission to index are granted.

Looks like `${user_name}` contain dot when applied index filter...

Ldap config from securityconfig/config.yml:

```
ldap:
...
        authentication_backend:
          type: "ldap"
          config:
            usersearch: "(sAMAccountName={0})"
            username_attribute: sAMAccountName
authz:
...
      roles_from_myldap:
        authorization_backend:
          type: "ldap"
          config:
            rolesearch: "(member={0})"
            userroleattribute: null
            userrolename: "disabled"
            rolename: "cn"
            resolve_nested_roles: true
            usersearch: "(sAMAccountName={0})"
```
