### ISSUE TITLE
Feature Request : parameter substitution in tenant patterns.

### ISSUE THREAD

**Issue by chrousto** [opensearch-project/security#817]
Hello all,

I have a question regarding parameter substitution and tenants patterns in roles that I think would constitute an interesting enhancement.
(I have posted this in the forum, [here](https://discuss.opendistrocommunity.dev/t/tenants-and-parameter-substitution/4038) but it did not get much attention so I am taking the initiative to repost this here as a Feature Request / enhancement, sorry for the cross-post)

The Feature is this :
I would like to have parameter substitution for tenant patterns in roles (for the moment, my understanding is that it is only available for index permissions as well as dls : https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/users-roles/#create-users).

The idea would be that this user :
```yaml
new-user:
  hash: "*************"
  reserved: false
  hidden: false
  opendistro_security_roles:
  - "role-tenant1"
  attributes:
    attribute1: "tenant1"
  static: false
```
Would only have access to the tenant tenant1 if the role role-tenant1 was defined like this :

```yaml
role-tenant1:
 reserved: false
 hidden: false
 cluster_permissions:
 - "read"
 - "cluster:monitor/nodes/stats"
 - "cluster:monitor/task/get"
 tenant_permissions:
 - tenant_patterns:
   - ${attr.internal.attribute1}
   allowed_actions:
   - "kibana_all_write"
 static: false
_meta:
 type: "roles"
 config_version: 2
```
I did not find anything on the roadmap yet or any feature request regarding this, do you think this would be an interesting feature to add ?

Thanks in advance.
Christophe.
