### ISSUE TITLE
Role definitions are not respected

### ISSUE THREAD

**Issue by tekollt** [opensearch-project/security#82]
I have a tenant named `TEST-TENANT`
```
TEST-TENANT:
  reserved: false
  hidden: false
  description: "Test Opendistro Tenants and Security"
  static: false
```
I then have three roles, one that gives READ to the tenant, another that gives readwrite a third that grants permissions to indexes so we have a single place to manage it for both of the other roles. While have granular access to dashboards and what not.
```
ROLE-TEST-READ:
  reserved: false
  hidden: false
  cluster_permissions: []
  index_permissions: []
  tenant_permissions:
  - tenant_patterns:
    - "TEST*"
    allowed_actions:
    - "kibana_all_read"
  static: false
ROLE-TEST-READWRITE:
  reserved: false
  hidden: false
  cluster_permissions: []
  index_permissions: []
  tenant_permissions:
  - tenant_patterns:
    - "TEST*"
    allowed_actions:
    - "kibana_all_write"
  static: false
ROLE-TEST-INDICIES:
  reserved: false
  hidden: false
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "*TEST*"
    dls: ""
    fls: []
    masked_fields: []
    allowed_actions: []
  tenant_permissions: []
    static: false
```

The roles are then mapped to two backend roles (openID).
Both roles have mapping to the indicies role in elastic, while it is 1:1 for the read and readwrite role.

```
ROLE-TEST-READWRITE:
  reserved: false
  hidden: false
  backend_roles:
  - "TEST-LOGS-READWRITE"
  hosts:
  - "*"
  users:
  - "*"
  and_backend_roles: []
ROLE-TEST-READ:
  reserved: false
  hidden: false
  backend_roles:
  - "TEST-LOGS-READ"
  hosts:
  - "*"
  users:
  - "*"
  and_backend_roles: []
ROLE-TEST-INDICIES:
  reserved: false
  hidden: false
  backend_roles:
  - "TEST-LOGS-READ"
  - "TEST-LOGS-READWRITE"
  hosts:
  - "*"
  users:
  - "*"
  and_backend_roles: []
```

The problem is that the role seems to not be respected. I have READ/WRITE permission to the tenant, even if i am only assigned to the backend role `TEST-LOGS-READ`    
If remove the role `TEST-LOGS-READWRITEs`  permission to the tenant, while still beeing assigned the access with the other role `TEST-LOGS-READ` - then the permission is respected and i have only READ access to the tenant. 

I have verified that the user is only part of a single backend role.   
We have also tried to remove the indicies role that is mapped to both backend roles.
