### ISSUE TITLE
anonymous and SAML authentication for Elasticsearch

### ISSUE THREAD

**Issue by reemBr** [opensearch-project/security#944]
hello everyone,

is it possible to allow both anonymous authentication and SAML authentication for elasticsearch?
I tried doing so with configuration like below, but then Kibana would give me samlConfigError whenever I set anonymous_auth_enabled: true. but would work fine otherwise.
Note that I only need the anonymous auth with Elasticsearch and not Kibana

```
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    kibana:
      # Kibana multitenancy
      multitenancy_enabled: true
      server_username: kibanaserver
      index: ".kibana"
    http:
      anonymous_auth_enabled: true
      xff:
        enabled: false
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      saml_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: ""
              entity_id: ""
            sp:
              entity_id: ""
            kibana_url: ""
            exchange_key: ""
        authentication_backend:
          type: noop

```
thank you,
